# Generated by Django 2.2 on 2019-04-14 20:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import members.models.activityinvite
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Navn")),
                (
                    "open_hours",
                    models.CharField(max_length=200, verbose_name="Tidspunkt"),
                ),
                (
                    "responsible_name",
                    models.CharField(max_length=200, verbose_name="Ansvarlig"),
                ),
                (
                    "responsible_contact",
                    models.EmailField(max_length=254, verbose_name="E-mail"),
                ),
                (
                    "placename",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Stednavn"
                    ),
                ),
                ("zipcode", models.CharField(max_length=4, verbose_name="Postnummer")),
                ("city", models.CharField(max_length=200, verbose_name="By")),
                (
                    "streetname",
                    models.CharField(max_length=200, verbose_name="Vejnavn"),
                ),
                (
                    "housenumber",
                    models.CharField(max_length=200, verbose_name="Husnummer"),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=200, verbose_name="Etage"),
                ),
                (
                    "door",
                    models.CharField(blank=True, max_length=200, verbose_name="Dør"),
                ),
                (
                    "dawa_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="DAWA id"
                    ),
                ),
                ("description", models.TextField(verbose_name="Beskrivelse")),
                (
                    "instructions",
                    models.TextField(
                        blank=True, verbose_name="Tilmeldings instruktioner"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start")),
                ("end_date", models.DateField(verbose_name="Slut")),
                (
                    "signup_closing",
                    models.DateField(null=True, verbose_name="Tilmelding lukker"),
                ),
                (
                    "updated_dtm",
                    models.DateTimeField(auto_now=True, verbose_name="Opdateret"),
                ),
                (
                    "open_invite",
                    models.BooleanField(default=False, verbose_name="Fri tilmelding"),
                ),
                (
                    "price_in_dkk",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        help_text="På prisen for aktiviteten fratrækker vi automatisk 75 kr. pr. barn hvis det er en sæsonaktivitet.",
                        max_digits=10,
                        verbose_name="Pris",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Max deltagere"
                    ),
                ),
                (
                    "max_age",
                    models.PositiveIntegerField(
                        default=17, verbose_name="Maximum Alder"
                    ),
                ),
                (
                    "min_age",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Minimum Alder"
                    ),
                ),
                (
                    "member_justified",
                    models.BooleanField(
                        default=True,
                        help_text="Bestemmer om personerne bliver til medlemmer i forhold til DUF. De fleste aktiviteter er sæsoner og medlemsberettiget. Hvis du er i tvivl, så spørg på Slack i #medlemsssystem-support.",
                        verbose_name="Aktiviteten gør personen til medlem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aktivitet",
                "verbose_name_plural": "Aktiviteter",
                "ordering": ["department__zipcode", "start_date"],
            },
        ),
        migrations.CreateModel(
            name="ActivityParticipant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added_dtm",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Tilmeldt"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, verbose_name="Besked / Note til arrangement"
                    ),
                ),
                (
                    "photo_permission",
                    models.CharField(
                        choices=[("OK", "Tilladelse givet"), ("NO", "Ikke tilladt")],
                        default="NO",
                        max_length=2,
                        verbose_name="Foto tilladelse",
                    ),
                ),
                (
                    "contact_visible",
                    models.BooleanField(
                        default=False,
                        verbose_name="Kontaktoplysninger synlige for andre holddeltagere",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.Activity",
                    ),
                ),
            ],
            options={"verbose_name": "Deltager", "verbose_name_plural": "Deltagere"},
        ),
        migrations.CreateModel(
            name="DailyStatisticsGeneral",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Kørsels tidspunkt",
                    ),
                ),
                ("persons", models.IntegerField(default=0, verbose_name="Personer")),
                (
                    "children_male",
                    models.IntegerField(default=0, verbose_name="Børn Drenge"),
                ),
                (
                    "children_female",
                    models.IntegerField(default=0, verbose_name="Børn Piger"),
                ),
                ("children", models.IntegerField(default=0, verbose_name="Børn")),
                (
                    "volunteers_male",
                    models.IntegerField(default=0, verbose_name="Frivillige Mænd"),
                ),
                (
                    "volunteers_female",
                    models.IntegerField(default=0, verbose_name="Frivillige Kvinder"),
                ),
                (
                    "volunteers",
                    models.IntegerField(default=0, verbose_name="Frivillige"),
                ),
                (
                    "departments",
                    models.IntegerField(default=0, verbose_name="Afdelinger"),
                ),
                (
                    "unions",
                    models.IntegerField(default=0, verbose_name="Lokalforeninger"),
                ),
                (
                    "waitinglist_male",
                    models.IntegerField(default=0, verbose_name="Drenge på venteliste"),
                ),
                (
                    "waitinglist_female",
                    models.IntegerField(default=0, verbose_name="Piger på venteliste"),
                ),
                (
                    "waitinglist",
                    models.IntegerField(
                        default=0, verbose_name="Personer på venteliste"
                    ),
                ),
                (
                    "family_visits",
                    models.IntegerField(
                        default=0, verbose_name="Profilsider besøgt foregående 24 timer"
                    ),
                ),
                (
                    "dead_profiles",
                    models.IntegerField(
                        default=0, verbose_name="Profilsider efterladt over et år"
                    ),
                ),
                (
                    "current_activity_participants",
                    models.IntegerField(
                        default=0, verbose_name="Deltagere på aktiviteter"
                    ),
                ),
                (
                    "activity_participants",
                    models.IntegerField(
                        default=0, verbose_name="Deltagere på aktiviteter over al tid"
                    ),
                ),
                (
                    "activity_participants_male",
                    models.IntegerField(
                        default=0,
                        verbose_name="Deltagere på aktiviteter over al tid (drenge)",
                    ),
                ),
                (
                    "activity_participants_female",
                    models.IntegerField(
                        default=0,
                        verbose_name="Deltagere på aktiviteter over al tid (piger)",
                    ),
                ),
                (
                    "payments",
                    models.IntegerField(default=0, verbose_name="Betalinger sum"),
                ),
                (
                    "payments_transactions",
                    models.IntegerField(
                        default=0, verbose_name="Betalinger transaktioner"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyStatisticsRegion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Kørsels tidspunkt",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("DK01", "Hovedstaden"),
                            ("DK02", "Sjælland"),
                            ("DK03", "Syddanmark"),
                            ("DK04", "Midtjylland"),
                            ("DK05", "Nordjylland"),
                        ],
                        max_length=4,
                        verbose_name="Region",
                    ),
                ),
                (
                    "departments",
                    models.IntegerField(default=0, verbose_name="Afdelinger"),
                ),
                (
                    "active_activities",
                    models.IntegerField(
                        default=0, verbose_name="Aktiviteter der er igang"
                    ),
                ),
                (
                    "activities",
                    models.IntegerField(default=0, verbose_name="Aktiviteter i alt"),
                ),
                (
                    "current_activity_participants",
                    models.IntegerField(
                        default=0, verbose_name="Deltagere på aktiviteter"
                    ),
                ),
                (
                    "activity_participants",
                    models.IntegerField(
                        default=0, verbose_name="Deltagere på aktiviteter over al tid"
                    ),
                ),
                ("members", models.IntegerField(default=0, verbose_name="Medlemmer")),
                (
                    "waitinglist",
                    models.IntegerField(default=0, verbose_name="Venteliste"),
                ),
                ("payments", models.IntegerField(default=0, verbose_name="Betalinger")),
                (
                    "volunteers_male",
                    models.IntegerField(default=0, verbose_name="Frivillige Mænd"),
                ),
                (
                    "volunteers_female",
                    models.IntegerField(default=0, verbose_name="Frivillige Kvinder"),
                ),
                (
                    "volunteers",
                    models.IntegerField(default=0, verbose_name="Frivillige"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Vi tilføjer automatisk "Coding Pirates" foran navnet når vi nævner det de fleste steder på siden.',
                        max_length=200,
                        verbose_name="Navn",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Beskrivelse af afdeling"
                    ),
                ),
                (
                    "open_hours",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Åbningstid"
                    ),
                ),
                (
                    "responsible_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Afdelingsleder"
                    ),
                ),
                (
                    "responsible_contact",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "placename",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Stednavn"
                    ),
                ),
                ("zipcode", models.CharField(max_length=10, verbose_name="Postnummer")),
                ("city", models.CharField(max_length=200, verbose_name="By")),
                (
                    "streetname",
                    models.CharField(max_length=200, verbose_name="Vejnavn"),
                ),
                (
                    "housenumber",
                    models.CharField(max_length=10, verbose_name="Husnummer"),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=10, verbose_name="Etage"),
                ),
                (
                    "door",
                    models.CharField(blank=True, max_length=10, verbose_name="Dør"),
                ),
                (
                    "dawa_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="DAWA id"
                    ),
                ),
                (
                    "has_waiting_list",
                    models.BooleanField(default=True, verbose_name="Venteliste"),
                ),
                (
                    "updated_dtm",
                    models.DateTimeField(auto_now=True, verbose_name="Opdateret"),
                ),
                (
                    "created",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Oprettet"
                    ),
                ),
                (
                    "closed_dtm",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="Lukket"
                    ),
                ),
                (
                    "isVisible",
                    models.BooleanField(
                        default=True, verbose_name="Kan ses på afdelingssiden"
                    ),
                ),
                (
                    "isOpening",
                    models.BooleanField(
                        default=False, verbose_name="Er afdelingen under opstart"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Hjemmeside")),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Længdegrad",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Breddegrad",
                    ),
                ),
                (
                    "onMap",
                    models.BooleanField(
                        default=True, verbose_name="Skal den være på kortet?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Afdeling",
                "verbose_name_plural": "Afdelinger",
                "ordering": ["zipcode"],
            },
        ),
        migrations.CreateModel(
            name="EmailItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reciever", models.EmailField(max_length=254)),
                ("bounce_token", models.UUIDField(default=uuid.uuid4)),
                (
                    "created_dtm",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oprettet"),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="Emne"),
                ),
                (
                    "body_html",
                    models.TextField(blank=True, verbose_name="HTML Indhold"),
                ),
                (
                    "body_text",
                    models.TextField(blank=True, verbose_name="Text Indhold"),
                ),
                (
                    "sent_dtm",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sendt tidstempel"
                    ),
                ),
                (
                    "send_error",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=200,
                        verbose_name="Fejl i afsendelse",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="members.Activity",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="members.Department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idname",
                    models.SlugField(unique=True, verbose_name="Unikt reference navn"),
                ),
                (
                    "updated_dtm",
                    models.DateTimeField(auto_now=True, verbose_name="Sidst redigeret"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Skabelon navn"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=200, verbose_name="Skabelon beskrivelse"
                    ),
                ),
                (
                    "template_help",
                    models.TextField(
                        blank=True, verbose_name="Hjælp omkring template variable"
                    ),
                ),
                ("from_address", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200, verbose_name="Emne")),
                (
                    "body_html",
                    models.TextField(blank=True, verbose_name="HTML Indhold"),
                ),
                (
                    "body_text",
                    models.TextField(blank=True, verbose_name="Text Indhold"),
                ),
            ],
            options={
                "verbose_name": "Email Skabelon",
                "verbose_name_plural": "Email Skabeloner",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_dtm",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oprettet"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=200,
                        null=True,
                        verbose_name="Mærke",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=200,
                        null=True,
                        verbose_name="Model",
                    ),
                ),
                (
                    "serial",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=200,
                        null=True,
                        verbose_name="Serienummer",
                    ),
                ),
                ("count", models.IntegerField(default=1, verbose_name="Antal enheder")),
                (
                    "link",
                    models.URLField(blank=True, verbose_name="Link til mere info"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Generelle noter")),
                (
                    "buy_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Købs pris",
                    ),
                ),
                (
                    "buy_place",
                    models.TextField(blank=True, null=True, verbose_name="Købs sted"),
                ),
                (
                    "buy_date",
                    models.DateField(blank=True, null=True, verbose_name="Købs dato"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.Department",
                    ),
                ),
            ],
            options={"verbose_name": "Udstyr", "verbose_name_plural": "Udstyr"},
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "dont_send_mails",
                    models.BooleanField(
                        default=False, verbose_name="Vil ikke kontaktes"
                    ),
                ),
                (
                    "updated_dtm",
                    models.DateTimeField(auto_now=True, verbose_name="Opdateret"),
                ),
                (
                    "confirmed_dtm",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bekræftet"
                    ),
                ),
                (
                    "last_visit_dtm",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sidst besøgt"
                    ),
                ),
                (
                    "deleted_dtm",
                    models.DateTimeField(blank=True, null=True, verbose_name="Slettet"),
                ),
            ],
            options={
                "verbose_name": "Familie",
                "verbose_name_plural": "Familier",
                "permissions": (
                    (
                        "view_family_unique",
                        "Can view family UUID field (password) - gives access to address",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Tilføjet"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("CA", "Kontant betaling"),
                            ("BA", "Bankoverførsel"),
                            ("CC", "Kreditkort"),
                            ("RE", "Refunderet"),
                            ("OT", "Andet"),
                        ],
                        default="CA",
                        max_length=2,
                        verbose_name="Type",
                    ),
                ),
                ("body_text", models.TextField(verbose_name="Beskrivelse")),
                (
                    "amount_ore",
                    models.IntegerField(default=0, verbose_name="Beløb i øre"),
                ),
                (
                    "confirmed_dtm",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bekræftet"
                    ),
                ),
                (
                    "cancelled_dtm",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Annulleret"
                    ),
                ),
                (
                    "refunded_dtm",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Refunderet"
                    ),
                ),
                (
                    "rejected_dtm",
                    models.DateTimeField(blank=True, null=True, verbose_name="Afvist"),
                ),
                (
                    "rejected_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Afvist årsag"
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.Activity",
                    ),
                ),
                (
                    "activityparticipant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.ActivityParticipant",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="members.Family"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membertype",
                    models.CharField(
                        choices=[
                            ("PA", "Forælder"),
                            ("GU", "Værge"),
                            ("CH", "Barn"),
                            ("NA", "Anden"),
                        ],
                        default="PA",
                        max_length=2,
                        verbose_name="Type",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Navn")),
                (
                    "zipcode",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Postnummer"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=200, verbose_name="By"),
                ),
                (
                    "streetname",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Vejnavn"
                    ),
                ),
                (
                    "housenumber",
                    models.CharField(
                        blank=True, max_length=5, verbose_name="Husnummer"
                    ),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=3, verbose_name="Etage"),
                ),
                (
                    "door",
                    models.CharField(blank=True, max_length=5, verbose_name="Dør"),
                ),
                (
                    "dawa_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="DAWA id"
                    ),
                ),
                (
                    "municipality",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Kommune"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Længdegrad",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Breddegrad",
                    ),
                ),
                (
                    "updated_dtm",
                    models.DateTimeField(auto_now=True, verbose_name="Opdateret"),
                ),
                (
                    "placename",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Stednavn"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("MA", "Dreng"), ("FM", "Pige")],
                        default=None,
                        max_length=20,
                        null=True,
                        verbose_name="Køn",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="Fødselsdag"),
                ),
                (
                    "has_certificate",
                    models.DateField(blank=True, null=True, verbose_name="Børneattest"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Noter"),
                ),
                (
                    "added",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Tilføjet"
                    ),
                ),
                (
                    "deleted_dtm",
                    models.DateTimeField(blank=True, null=True, verbose_name="Slettet"),
                ),
                (
                    "address_invalid",
                    models.BooleanField(default=False, verbose_name="Ugyldig adresse"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.Family"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "Personer",
                "ordering": ["added"],
                "permissions": (
                    (
                        "view_full_address",
                        "Can view persons full address + phonenumber + email",
                    ),
                    ("view_all_persons", "Can view persons not related to department"),
                ),
            },
        ),
        migrations.CreateModel(
            name="Union",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Foreningens navn"),
                ),
                (
                    "chairman",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Formand"
                    ),
                ),
                (
                    "chairman_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Formandens email"
                    ),
                ),
                (
                    "second_chair",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Næstformand"
                    ),
                ),
                (
                    "second_chair_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Næstformandens email"
                    ),
                ),
                (
                    "cashier",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Kasserer"
                    ),
                ),
                (
                    "cashier_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Kassererens email"
                    ),
                ),
                (
                    "secretary",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Sekretær"
                    ),
                ),
                (
                    "secratary_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Sekretærens email"
                    ),
                ),
                (
                    "union_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Foreningens email"
                    ),
                ),
                (
                    "statues",
                    models.URLField(
                        blank=True, verbose_name="Link til gældende vedtægter"
                    ),
                ),
                (
                    "founded",
                    models.DateField(blank=True, null=True, verbose_name="Stiftet"),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("S", "Sjælland"),
                            ("J", "Jylland"),
                            ("F", "Fyn"),
                            ("Ø", "Øer"),
                        ],
                        max_length=1,
                        verbose_name="region",
                    ),
                ),
                (
                    "placename",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Stednavn"
                    ),
                ),
                ("zipcode", models.CharField(max_length=10, verbose_name="Postnummer")),
                ("city", models.CharField(max_length=200, verbose_name="By")),
                (
                    "streetname",
                    models.CharField(max_length=200, verbose_name="Vejnavn"),
                ),
                (
                    "housenumber",
                    models.CharField(max_length=10, verbose_name="Husnummer"),
                ),
                (
                    "floor",
                    models.CharField(blank=True, max_length=10, verbose_name="Etage"),
                ),
                (
                    "door",
                    models.CharField(blank=True, max_length=10, verbose_name="Dør"),
                ),
                (
                    "boardMembers",
                    models.TextField(blank=True, verbose_name="Menige medlemmer"),
                ),
                (
                    "bank_main_org",
                    models.BooleanField(
                        default=True,
                        verbose_name="Sæt kryds hvis I har konto hos hovedforeningen (og ikke har egen bankkonto).",
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True,
                        help_text="Kontonummer i formatet 1234-1234567890",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Indtast kontonummer i det rigtige format.",
                                regex="^[0-9]{4} *?-? *?[0-9]{6,10} *?$",
                            )
                        ],
                        verbose_name="Bankkonto:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forening",
                "verbose_name_plural": "Foreninger",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ZipcodeRegion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("DK01", "Hovedstaden"),
                            ("DK02", "Sjælland"),
                            ("DK03", "Syddanmark"),
                            ("DK04", "Midtjylland"),
                            ("DK05", "Nordjylland"),
                        ],
                        max_length=4,
                        verbose_name="Region",
                    ),
                ),
                ("zipcode", models.CharField(max_length=4, verbose_name="Postnummer")),
                ("city", models.CharField(max_length=200, verbose_name="By")),
                ("municipalcode", models.IntegerField(verbose_name="Kommunekode")),
                ("municipalname", models.TextField(verbose_name="Kommunenavn")),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Længdegrad",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Breddegrad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaitingList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "on_waiting_list_since",
                    models.DateTimeField(verbose_name="Venteliste position"),
                ),
                (
                    "added_dtm",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Tilføjet"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.Department",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.Person"
                    ),
                ),
            ],
            options={
                "verbose_name": "På venteliste",
                "verbose_name_plural": "På ventelister",
                "ordering": ["on_waiting_list_since"],
            },
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "added",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Start"
                    ),
                ),
                (
                    "confirmed",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Bekræftet"
                    ),
                ),
                (
                    "removed",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Slut"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.Department",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.Person"
                    ),
                ),
            ],
            options={"verbose_name": "Frivillig", "verbose_name_plural": "Frivillige"},
        ),
        migrations.CreateModel(
            name="QuickpayTransaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        verbose_name="Link til Quickpay formular",
                    ),
                ),
                (
                    "transaction_id",
                    models.IntegerField(
                        default=None, null=True, verbose_name="Transaktions ID"
                    ),
                ),
                (
                    "amount_ore",
                    models.IntegerField(default=0, verbose_name="Beløb i øre"),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Quickpay order id",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.Payment",
                    ),
                ),
                (
                    "refunding",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.QuickpayTransaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="payment",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="members.Person",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_info_dtm",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bedt om opdatering af info"
                    ),
                ),
                (
                    "warned_deletion_info_dtm",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Advaret om sletning fra liste",
                    ),
                ),
                (
                    "anounced_activity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.Activity",
                    ),
                ),
                (
                    "anounced_activity_participant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.ActivityParticipant",
                    ),
                ),
                (
                    "anounced_department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.Department",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.EmailItem",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.Family"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "member_since",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Indmeldt"
                    ),
                ),
                (
                    "member_until",
                    models.DateField(
                        blank=True, default=None, null=True, verbose_name="Udmeldt"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.Department",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="members.Person"
                    ),
                ),
            ],
            options={
                "verbose_name": "Medlem",
                "verbose_name_plural": "Medlemmer",
                "ordering": ["is_active", "member_since"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentLoan",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(default=1, verbose_name="Antal enheder udlånt"),
                ),
                (
                    "loaned_dtm",
                    models.DateField(auto_now_add=True, verbose_name="Udlånt"),
                ),
                (
                    "expected_back_dtm",
                    models.DateField(
                        blank=True, null=True, verbose_name="Forventet returneret"
                    ),
                ),
                (
                    "returned_dtm",
                    models.DateField(blank=True, null=True, verbose_name="Afleveret"),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Noter")),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.Department",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.Equipment",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.Person"
                    ),
                ),
            ],
            options={
                "verbose_name": "Udstyrs udlån",
                "verbose_name_plural": "Udstyrs udlån",
            },
        ),
        migrations.AddField(
            model_name="equipment",
            name="union",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.Union",
            ),
        ),
        migrations.AddField(
            model_name="emailitem",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.Family",
            ),
        ),
        migrations.AddField(
            model_name="emailitem",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.Person",
            ),
        ),
        migrations.AddField(
            model_name="emailitem",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="members.EmailTemplate",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="union",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="members.Union",
                verbose_name="Lokalforening",
            ),
        ),
        migrations.CreateModel(
            name="DailyStatisticsUnion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Kørsels tidspunkt",
                    ),
                ),
                (
                    "departments",
                    models.IntegerField(default=0, verbose_name="Afdelinger"),
                ),
                (
                    "active_activities",
                    models.IntegerField(
                        default=0, verbose_name="Aktiviteter der er igang"
                    ),
                ),
                (
                    "activities",
                    models.IntegerField(default=0, verbose_name="Aktiviteter i alt"),
                ),
                (
                    "current_activity_participants",
                    models.IntegerField(
                        default=0, verbose_name="Deltagere på aktiviteter"
                    ),
                ),
                (
                    "activity_participants",
                    models.IntegerField(
                        default=0, verbose_name="Deltagere på aktiviteter over al tid"
                    ),
                ),
                ("members", models.IntegerField(default=0, verbose_name="Medlemmer")),
                (
                    "waitinglist",
                    models.IntegerField(default=0, verbose_name="Venteliste"),
                ),
                ("payments", models.IntegerField(default=0, verbose_name="Betalinger")),
                (
                    "volunteers_male",
                    models.IntegerField(default=0, verbose_name="Frivillige Mænd"),
                ),
                (
                    "volunteers_female",
                    models.IntegerField(default=0, verbose_name="Frivillige Kvinder"),
                ),
                (
                    "volunteers",
                    models.IntegerField(default=0, verbose_name="Frivillige"),
                ),
                (
                    "union",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.Union"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyStatisticsDepartment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Kørsels tidspunkt",
                    ),
                ),
                (
                    "active_activities",
                    models.IntegerField(
                        default=0, verbose_name="Aktiviteter der er igang"
                    ),
                ),
                (
                    "activities",
                    models.IntegerField(default=0, verbose_name="Aktiviteter i alt"),
                ),
                (
                    "current_activity_participants",
                    models.IntegerField(
                        default=0, verbose_name="Deltagere på aktiviteter"
                    ),
                ),
                (
                    "activity_participants",
                    models.IntegerField(
                        default=0, verbose_name="Deltagere på aktiviteter over al tid"
                    ),
                ),
                ("members", models.IntegerField(default=0, verbose_name="Medlemmer")),
                (
                    "waitinglist",
                    models.IntegerField(default=0, verbose_name="Venteliste"),
                ),
                (
                    "waitingtime",
                    models.DurationField(default=0, verbose_name="Ventetid"),
                ),
                ("payments", models.IntegerField(default=0, verbose_name="Betalinger")),
                (
                    "volunteers_male",
                    models.IntegerField(default=0, verbose_name="Frivillige Mænd"),
                ),
                (
                    "volunteers_female",
                    models.IntegerField(default=0, verbose_name="Frivillige Kvinder"),
                ),
                (
                    "volunteers",
                    models.IntegerField(default=0, verbose_name="Frivillige"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.Department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminUserInformation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departments", models.ManyToManyField(to="members.Department")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="members.Member"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="members.Department"
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="union",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.Union",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activityparticipant", unique_together={("activity", "member")}
        ),
        migrations.CreateModel(
            name="ActivityInvite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invite_dtm",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Inviteret"
                    ),
                ),
                (
                    "expire_dtm",
                    models.DateField(
                        default=members.models.activityinvite._defaultInviteExpiretime,
                        verbose_name="Udløber",
                    ),
                ),
                (
                    "rejected_dtm",
                    models.DateField(blank=True, null=True, verbose_name="Afslået"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.Activity",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.Person"
                    ),
                ),
            ],
            options={
                "verbose_name": "Invitation",
                "verbose_name_plural": "Invitationer",
                "unique_together": {("activity", "person")},
            },
        ),
    ]
