# Generated by Django 2.2.2 on 2019-06-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0002_auto_20190507_2141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="union",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.Union",
            ),
        ),
    ]
