# Generated by Django 2.2.3 on 2019-07-31 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20190618_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPaymentTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tilføjet')),
                ('payment_type', models.CharField(choices=[('CA', 'Kontant betaling'), ('BA', 'Bankoverførsel'), ('CC', 'Kreditkort'), ('RE', 'Refunderet'), ('OT', 'Andet')], default='CA', max_length=2, verbose_name='Type')),
                ('body_text', models.TextField(verbose_name='Beskrivelse')),
                ('amount_ore', models.IntegerField(default=0, verbose_name='Beløb i øre')),
                ('status', models.CharField(choices=[('NE', 'Ny transaktion'), ('CO', 'Betalt'), ('CA', 'Annulleret'), ('RE', 'Refunderet'), ('NO', 'Afvist')], default='NE', max_length=2, verbose_name='Status')),
                ('rejected_message', models.TextField(blank=True, null=True, verbose_name='Afvist årsag')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.Person')),
            ],
        ),
    ]
