# Generated by Django 2.2.2 on 2019-06-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='postal_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.Address'),
        ),
    ]
