# Generated by Django 2.2.3 on 2019-07-31 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_newpaymenttemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpaymenttemp',
            name='confirmed_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bekræftet'),
        ),
        migrations.AddField(
            model_name='newpaymenttemp',
            name='rejected_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Afvist'),
        ),
        migrations.AddField(
            model_name='newpaymenttemp',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Eksternt ID')
        ),
        migrations.AlterField(
            model_name='newpaymenttemp',
            name='status',
            field=models.CharField(choices=[('NEW', 'Ny transaktion'), ('CANCELLED', 'Annulleret'), ('REFUNDED', 'Refunderet')], default='NEW', max_length=9, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='activityparticipant',
            name='payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='members.NewPaymentTemp'),
        ),
    ]