# Generated by Django 2.2.2 on 2019-06-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_person_postal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='placename',
            field=models.CharField(blank=True, max_length=200, verbose_name='Stednavn'),
        ),
        migrations.AddField(
            model_name='department',
            name='municipality',
            field=models.CharField(blank=True, null=True, max_length=100, verbose_name='Kommune')
        ),
        migrations.AddField(
            model_name='person',
            name='address_moved',
            field=models.BooleanField(default=False, verbose_name='Adresse flyttet'),
        ),
        migrations.AddField(
            model_name='activity',
            name='address_moved',
            field=models.BooleanField(default=False, verbose_name='Adresse flyttet')
        ),
        migrations.AddField(
            model_name='department',
            name='address_moved',
            field=models.BooleanField(default=False, verbose_name='Adresse flyttet')
        ),
        migrations.AddField(
            model_name='union',
            name='address_moved',
            field=models.BooleanField(default=False, verbose_name='Adresse flyttet')
        ),
        migrations.AlterField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='By'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dawa_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='DAWA id'),
        ),
        migrations.AlterField(
            model_name='person',
            name='door',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Dør'),
        ),
        migrations.AlterField(
            model_name='person',
            name='floor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Etage'),
        ),
        migrations.AlterField(
            model_name='person',
            name='housenumber',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Husnummer'),
        ),
        migrations.AlterField(
            model_name='person',
            name='placename',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stednavn'),
        ),
        migrations.AlterField(
            model_name='person',
            name='streetname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Vejnavn'),
        ),
        migrations.AlterField(
            model_name='person',
            name='zipcode',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Postnummer'),
        ),
    ]
