# Generated by Django 2.2.3 on 2019-07-31 11:18
# This migration will be used to convert payments so charges and refunds are on
# separate lines rather than the same line.

from django.db import migrations


def convert_payments(apps, schema_editor):
    Payment = apps.get_model("members", "Payment")
    tempPay = apps.get_model("members", "NewPaymentTemp")
    for pay in Payment.objects.all():
        # We go through each object making sure it is not refunded or cancelled
        # If it is, we need to create another transaction for that. Before starting
        # we always note the original primary key in the old_pk field so we can
        # adjust quickpays id's afterwards
        # In all cases create transaction
        
        if pay.refunded_dtm is not None:
            # Transaction is refunded
            # Create refund transaction
            echo "Test"

        if pay.cancelled_dtm is not None:
            # Transaction has been cancelled.
            # Check it has not been refunded.
            # If it has not been refunded, create cancel transaction.
            echo "Testing"

def reverse_convert_payments(apps, schema_editor):
    Payment = apps.get_model("members", "Payment")
    tempPay = apps.get_model("members", "NewPaymentTemp")

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20190731_1407'),
    ]

    operations = [
        migrations.RunPython(convert_payments, reverse_convert_payments)
    ]
