# Generated by Django 2.2.3 on 2019-07-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20190627_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_invalid',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=200, verbose_name='By'),
        ),
        migrations.AlterField(
            model_name='address',
            name='housenumber',
            field=models.CharField(max_length=5, verbose_name='Husnummer'),
        ),
        migrations.AlterField(
            model_name='address',
            name='streetname',
            field=models.CharField(max_length=200, verbose_name='Vejnavn'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=4, verbose_name='Postnummer'),
        ),
    ]
