# Generated by Django 2.2.8 on 2019-12-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0006_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="members.Address",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                help_text='Vi tilføjer automatisk "Coding Pirates" foran navnet når vi\n    nævner det de fleste steder på siden.',
                max_length=200,
                verbose_name="Navn",
            ),
        ),
    ]
