# Generated by Django 2.2.4 on 2019-08-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20190731_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RenameModel(
            old_name='NewPaymentTemp',
            new_name='Payment',
        ),
    ]
