# Generated by Django 2.2.8 on 2019-12-30 16:46

from django.db import migrations
import django.db.models.deletion


from members.models import Department, Address


def department_add_address(_apps, _schema_editor):
    for department in Department.objects.all():
        if department.dawa_id != "":
            address = Address.get_by_dawa_id(department.dawa_id)
        else:
            address = Address(
                streetname=department.streetname,
                housenumber=department.housenumber,
                floor=department.floor,
                door=department.door,
                city=department.city,
                zipcode=department.zipcode,
            )
            try:
                address.save()
            except django.db.utils.IntegrityError:
                address = None
        department.address = address
        department.save()


def department_remove_address(_apps, _schema_editor):
    for address in Address.objects.all():
        deps = Department.objects.filter(address=address)
        for dep in deps:
            dep.zipcode = address.zipcodockde
            dep.city = address.city
            dep.streetname = address.streetname
            dep.floor = address.floor
            dep.door = address.door
            dep.save()
        address.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_add_address_model_department"),
    ]

    operations = [
        migrations.RunPython(department_add_address, department_remove_address),
    ]
