# Generated by Django 2.2.4 on 2019-08-20 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20190812_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityparticipant',
            name='removed_dtm',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Afmeldt'),
        ),
        migrations.AddField(
            model_name='activityparticipant',
            name='removed_note',
            field=models.TextField(blank=True, verbose_name='Afmeldingsnote'),
        ),
        migrations.AlterField(
            model_name='activityparticipant',
            name='added_dtm',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tilmeldt'),
        ),
    ]
