# Generated by Django 2.2.4 on 2019-08-20 09:14

from django.db import migrations, models
import django.db.models.deletion


def add_person_to_actpar(apps, schema_editor):
    actPar = apps.get_model("members", "ActivityParticipant")
    for ap in actPar.objects.all():
        ap.person = ap.member.person
        ap.save()


def remove_person_from_actpar(apps, schema_editor):
    actPar = apps.get_model("members", "ActivityParticipant")
    for ap in actPar.objects.all():
        ap.person = None
        ap.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20190820_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityparticipant',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='members.Person'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='external_id',
            field=models.IntegerField(verbose_name='Eksternt ID'),
        ),
        migrations.RunPython(add_person_to_actpar, remove_person_from_actpar),
    ]
