# Generated by Django 2.2.4 on 2019-08-20 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20190820_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityparticipant',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='members.Person'),
        ),
    ]
