# Generated by Django 2.2.8 on 2019-12-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0009_union_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuserinformation",
            name="unions",
            field=models.ManyToManyField(to="members.Union"),
        ),
    ]
