# Generated by Django 2.2.8 on 2020-01-02 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_adminuserinformation_unions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Adresse", "verbose_name_plural": "Adresser"},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "Afdeling", "verbose_name_plural": "Afdelinger"},
        ),
        migrations.RemoveField(model_name="department", name="city",),
        migrations.RemoveField(model_name="department", name="dawa_id",),
        migrations.RemoveField(model_name="department", name="door",),
        migrations.RemoveField(model_name="department", name="floor",),
        migrations.RemoveField(model_name="department", name="housenumber",),
        migrations.RemoveField(model_name="department", name="latitude",),
        migrations.RemoveField(model_name="department", name="longitude",),
        migrations.RemoveField(model_name="department", name="placename",),
        migrations.RemoveField(model_name="department", name="streetname",),
        migrations.RemoveField(model_name="department", name="zipcode",),
        migrations.RemoveField(model_name="union", name="city",),
        migrations.RemoveField(model_name="union", name="door",),
        migrations.RemoveField(model_name="union", name="floor",),
        migrations.RemoveField(model_name="union", name="housenumber",),
        migrations.RemoveField(model_name="union", name="placename",),
        migrations.RemoveField(model_name="union", name="streetname",),
        migrations.RemoveField(model_name="union", name="zipcode",),
        migrations.AddField(
            model_name="address",
            name="region",
            field=models.CharField(
                choices=[
                    ("Region Syddanmark", "Region Syddanmark"),
                    ("Region Hovedstaden", "Region Hovedstaden"),
                    ("Region Nordjylland", "Region Nordjylland"),
                    ("Region Midtjylland", "Region Midtjylland"),
                    ("Region Sjælland", "Region Sjælland"),
                ],
                max_length=20,
                null=True,
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="members.Address"
            ),
        ),
        migrations.AlterField(
            model_name="union",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="members.Address"
            ),
        ),
    ]
