# Generated by Django 2.2.8 on 2020-01-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0011_adminuserinformation_unions"),
    ]

    operations = [
        migrations.RemoveField(model_name="department", name="has_waiting_list",),
    ]
