# Generated by Django 2.2.8 on 2020-01-03 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0012_auto_20200103_1328"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="has_waiting_list",
        ),
    ]
