# Generated by Django 2.2.9 on 2020-01-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0016_auto_20200121_2342"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="door",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Dør"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="floor",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Etage"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="municipality",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Kommune"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="placename",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Stednavn"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="region",
            field=models.CharField(
                choices=[
                    ("Region Syddanmark", "Region Syddanmark"),
                    ("Region Hovedstaden", "Region Hovedstaden"),
                    ("Region Nordjylland", "Region Nordjylland"),
                    ("Region Midtjylland", "Region Midtjylland"),
                    ("Region Sjælland", "Region Sjælland"),
                ],
                default="",
                max_length=20,
                verbose_name="Region",
            ),
            preserve_default=False,
        ),
    ]
