# Generated by Django 2.2.9 on 2020-01-28 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0017_auto_20200125_1457"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="responsible_contact",
            new_name="department_email",
        ),
        migrations.RemoveField(model_name="department", name="onMap",),
        migrations.AddField(
            model_name="department",
            name="department_leader",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="members.Person",
            ),
            preserve_default=False,
        ),
    ]
