# Generated by Django 2.2.9 on 2020-01-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20200128_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_leader',
        ),
        migrations.AddField(
            model_name='department',
            name='department_leaders',
            field=models.ManyToManyField(to='members.Person'),
        ),
    ]
