# Generated by Django 2.2.9 on 2020-03-09 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0019_remove_union_region"),
        ("members", "0019_auto_20200211_1457"),
    ]

    operations = []
