# Generated by Django 2.2.9 on 2020-03-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0019_auto_20200211_1457"),
    ]

    operations = [
        migrations.AddField(
            model_name="union",
            name="meeting_notes",
            field=models.URLField(
                blank=True, verbose_name="Link til seneste referater"
            ),
        ),
    ]
