# Generated by Django 2.2.9 on 2020-02-19 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0019_auto_20200211_1457"),
        ("members", "0019_auto_20200203_1322"),
    ]

    operations = []
