# Generated by Django 2.2.9 on 2020-03-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0020_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="sign_up_date",
            field=models.DateField(verbose_name="Opskrivningsdato"),
        ),
    ]
