# Generated by Django 2.2.9 on 2020-04-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0020_merge_20200309_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="region",
            field=models.CharField(
                choices=[
                    ("Region Syddanmark", "Syddanmark"),
                    ("Region Hovedstaden", "Hovedstaden"),
                    ("Region Nordjylland", "Nordjylland"),
                    ("Region Midtjylland", "Midtjylland"),
                    ("Region Sjælland", "Sjælland"),
                ],
                max_length=20,
                verbose_name="Region",
            ),
        ),
    ]
