# Generated by Django 2.2.9 on 2020-03-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0021_payableitem_refunded"),
    ]

    operations = [
        migrations.AddField(
            model_name="payableitem",
            name="processed",
            field=models.BooleanField(default=False, verbose_name="Processed"),
        ),
    ]
