# Generated by Django 3.0.5 on 2020-04-13 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import members.models.season


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0021_auto_20200413_0930"),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Navn")),
                ("start_time", models.TimeField(verbose_name="Start Tidspunkt")),
                ("end_time", models.TimeField(verbose_name="Slut Tidspunkt")),
                ("description", models.TextField(verbose_name="Beskrivelse")),
                (
                    "instructions",
                    models.TextField(
                        blank=True, verbose_name="Tilmeldings instruktioner"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Start dato")),
                ("end_date", models.DateField(verbose_name="Slut dato")),
                (
                    "week_day",
                    models.IntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                (
                    "signup_closing",
                    models.DateField(
                        default=members.models.season._default_sign_up_close,
                        verbose_name="Tilmelding lukker",
                    ),
                ),
                (
                    "open_invite",
                    models.BooleanField(default=False, verbose_name="Fri tilmelding"),
                ),
                (
                    "price_in_dkk",
                    models.DecimalField(
                        decimal_places=2,
                        default=500,
                        help_text="Vi fratrækker automatisk 75 kr. til hovedforeningen",
                        max_digits=10,
                        verbose_name="Pris",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Max deltagere"
                    ),
                ),
                (
                    "max_age",
                    models.PositiveIntegerField(
                        default=17, verbose_name="Maximum Alder"
                    ),
                ),
                (
                    "min_age",
                    models.PositiveIntegerField(
                        default=7, verbose_name="Minimum Alder"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="members.Department",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="members.Person"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sæson",
                "verbose_name_plural": "Sæsoner",
                "ordering": ["department", "start_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="waitinglist",
            options={
                "ordering": ["on_waiting_list_since", "department"],
                "verbose_name": "På venteliste",
                "verbose_name_plural": "På ventelister",
            },
        ),
        migrations.AlterUniqueTogether(
            name="waitinglist", unique_together={("person", "department")},
        ),
        migrations.CreateModel(
            name="SeasonParticipant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sign_up_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Tilmeldt"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, verbose_name="Besked / Note til kaptajnen"
                    ),
                ),
                (
                    "photo_permission",
                    models.BooleanField(verbose_name="Foto tilladelse"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.Person"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="members.Season"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sæsondeltager",
                "verbose_name_plural": "Sæsondeltagere",
                "unique_together": {("season", "person")},
            },
        ),
        migrations.AddField(
            model_name="payableitem",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment",
                to="members.SeasonParticipant",
            ),
        ),
        migrations.CreateModel(
            name="SeasonInvite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invite_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Inviteret"
                    ),
                ),
                (
                    "rejected_date",
                    models.DateField(blank=True, null=True, verbose_name="Afslået"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.Person"
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.Season"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sæsoninvitation",
                "verbose_name_plural": "Sæsoninvitationer",
                "unique_together": {("season", "person")},
            },
        ),
    ]
