# Generated by Django 2.2.9 on 2020-03-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0021_auto_20200317_0115"),
    ]

    operations = [
        migrations.AddField(
            model_name="union",
            name="closed",
            field=models.DateField(blank=True, null=True, verbose_name="Lukket"),
        ),
    ]
