# Generated by Django 2.2.9 on 2020-05-26 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0021_auto_20200309_1107"),
        ("members", "0021_auto_20200406_1722"),
    ]

    operations = []
