# Generated by Django 2.2.9 on 2020-06-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_merge_20200526_1131'),
        ('members', '0022_merge_20200526_1130'),
    ]

    operations = [
    ]
