# Generated by Django 2.2.9 on 2020-03-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0022_union_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="union",
            name="membership_price",
            field=models.IntegerField(default=75, verbose_name="Medlemskontigent"),
        ),
    ]
