# Generated by Django 3.0.4 on 2020-03-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0023_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payableitem",
            options={
                "ordering": ["added"],
                "verbose_name": "Betaling",
                "verbose_name_plural": "Betalinger",
            },
        ),
    ]
