# Generated by Django 2.2.9 on 2020-06-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0023_merge_20200615_1116"),
    ]

    operations = [
        migrations.AlterField(
            model_name="union",
            name="founded",
            field=models.DateField(blank=True, null=True, verbose_name="Stiftet"),
        ),
    ]
