# Generated by Django 3.0.8 on 2020-09-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20200615_1244'),
        ('members', '0024_auto_20200902_1108'),
    ]

    operations = [
    ]
