# Generated by Django 3.1.1 on 2021-03-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0024_auto_20200902_1108"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Kort beskrivelse af aktivitetstype. Fx 'Støttemedlem'.",
                        max_length=50,
                        verbose_name="Aktivitetstype",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Uddyb gerne her hvad aktivitetstypen dækker over.",
                        max_length=200,
                        verbose_name="Beskrivelse",
                    ),
                ),
                (
                    "updated_dtm",
                    models.DateTimeField(auto_now=True, verbose_name="Opdateret"),
                ),
            ],
            options={
                "verbose_name": "Aktivitetstype",
                "verbose_name_plural": "Aktivitetstype",
                "ordering": ["name"],
            },
        ),
    ]
