# Generated by Django 3.0.5 on 2020-10-19 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20200413_1304'),
        ('members', '0024_auto_20200902_1108'),
    ]

    operations = [
    ]
