# Generated by Django 3.0.4 on 2020-03-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_payableitem_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='payableitem',
            name='confirmation_sent',
            field=models.BooleanField(default=False, verbose_name='Bekræftelse sendt'),
        ),
    ]
