# Generated by Django 3.0.4 on 2020-03-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_payableitem_confirmation_sent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
