# Generated by Django 3.2.13 on 2022-08-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0026_auto_20220425_2203"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[("", "(Vælg køn)"), ("MA", "Dreng"), ("FM", "Pige")],
                default=None,
                max_length=20,
                null=True,
                verbose_name="Køn",
            ),
        ),
    ]
