# Generated by Django 3.2.13 on 2022-10-30 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0028_auto_20221004_1338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="union",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.union",
                verbose_name="Forening",
            ),
        ),
    ]
