# Generated by Django 3.2.15 on 2022-11-01 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0030_auto_20221030_1230"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="member_justified",
            field=models.BooleanField(
                default=True,
                help_text="Bestemmer om personerne bliver til medlemmer i forhold til DUF. De fleste aktiviteter er forløb/sæsoner og medlemsberettiget. Hvis du er i tvivl, så spørg på Slack i #medlemsssystem-support.",
                verbose_name="Aktiviteten gør personen til medlem",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="price_in_dkk",
            field=models.DecimalField(
                decimal_places=2,
                default=500,
                help_text="Hvis det er et forløb / en sæsonaktivitet fratrækkes der automatisk 100 kr. til Coding Pirates Denmark pr. barn.",
                max_digits=10,
                verbose_name="Pris",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="closed_dtm",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Dato for lukning af denne afdeling",
                null=True,
                verbose_name="Lukket",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="created",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Dato for oprettelse af denne afdeling",
                verbose_name="Oprettet",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="isOpening",
            field=models.BooleanField(
                default=False,
                help_text="Er denne afdeling under opstart ?",
                verbose_name="Under opstart",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="isVisible",
            field=models.BooleanField(
                default=True,
                help_text="Bliver denne afdeling vist på https://codingpirates.dk/afdelinger/ ?",
                verbose_name="På afdelingskort",
            ),
        ),
    ]
