# Generated by Django 3.2.15 on 2022-11-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0030_auto_20221030_1230"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="refunded_dtm",
            new_name="refunded_at",
        ),
        migrations.AddField(
            model_name="payment",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Reminder sent"
            ),
        ),
    ]
