# Generated by Django 3.2.15 on 2022-11-20 12:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0031_auto_20221120_1215"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["added_at"],
                "permissions": (
                    (
                        "view_full_address",
                        "Can view persons full address + phonenumber + email",
                    ),
                    ("view_all_persons", "Can view persons not related to department"),
                ),
                "verbose_name": "Person",
                "verbose_name_plural": "Personer",
            },
        ),
        migrations.RenameField(
            model_name="activityinvite",
            old_name="rejected_dtm",
            new_name="rejected_at",
        ),
        migrations.RenameField(
            model_name="activityparticipant",
            old_name="added_dtm",
            new_name="added_at",
        ),
        migrations.RenameField(
            model_name="family",
            old_name="confirmed_dtm",
            new_name="confirmed_at",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="accepted_dtm",
            new_name="accepted_at",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="added",
            new_name="added_at",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="cancelled_dtm",
            new_name="cancelled_at",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="confirmed_dtm",
            new_name="confirmed_at",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="rejected_dtm",
            new_name="rejected_at",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="added",
            new_name="added_at",
        ),
        migrations.RenameField(
            model_name="volunteer",
            old_name="added",
            new_name="added_at",
        ),
        migrations.RenameField(
            model_name="waitinglist",
            old_name="added_dtm",
            new_name="added_at",
        ),
    ]
