# Generated by Django 3.2.15 on 2022-11-20 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0032_alter_activity_union"),
        ("members", "0032_auto_20221120_1355"),
    ]

    operations = []
