# Generated by Django 4.1.3 on 2022-12-29 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0033_merge_20221120_1548"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="created_at",
            field=models.DateTimeField(
                auto_created=True,
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Oprettet",
            ),
            preserve_default=False,
        ),
    ]
