# Generated by Django 4.1.4 on 2022-12-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0035_address_created_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="union",
            old_name="founded",
            new_name="founded_at",
        ),
        migrations.AddField(
            model_name="union",
            name="closed_at",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Dato for lukning af denne forening",
                null=True,
                verbose_name="Lukket",
            ),
        ),
    ]
