# Generated by Django 4.1.4 on 2023-02-26 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0036_rename_founded_union_founded_at_union_closed_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="waitinglist",
            options={
                "ordering": ["on_waiting_list_since"],
                "verbose_name": "Venteliste",
                "verbose_name_plural": "Ventelister",
            },
        ),
    ]
