# Generated by Django 4.1.6 on 2023-02-26 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0037_activityparticipant_person"),
        ("members", "0037_alter_waitinglist_options"),
    ]

    operations = []
