# Generated by Django 4.1.6 on 2023-03-18 13:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0038_merge_20230226_1633"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activityparticipant",
            unique_together={("activity", "person")},
        ),
        migrations.RemoveField(
            model_name="activityparticipant",
            name="member",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
    ]
