# Generated by Django 4.1.4 on 2023-03-18 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0037_alter_activityparticipant_note"),
        ("members", "0038_merge_20230226_1633"),
    ]

    operations = []
