# Generated by Django 4.1.6 on 2023-03-18 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0039_alter_activityparticipant_unique_together_and_more"),
        ("members", "0039_merge_20230318_1112"),
    ]

    operations = []
