# Generated by Django 4.2.2 on 2023-06-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0040_merge_20230318_1545"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="gender",
            field=models.CharField(
                choices=[
                    ("", "(Vælg køn)"),
                    ("MA", "Dreng"),
                    ("FM", "Pige"),
                    ("OT", "Andet"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="Køn",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="membertype",
            field=models.CharField(
                choices=[
                    ("PA", "Forælder"),
                    ("GU", "Værge"),
                    ("CH", "Barn"),
                    ("NA", "Andet"),
                ],
                default="PA",
                max_length=2,
                verbose_name="Type",
            ),
        ),
    ]
