# Generated by Django 4.2 on 2023-06-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0041_alter_person_gender_alter_person_membertype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="union",
            name="name",
            field=models.CharField(
                help_text='Vi tilføjer automatisk "Coding Pirates" foran navnet når vi\n    nævner det de fleste steder på siden.',
                max_length=200,
                verbose_name="Foreningens navn",
            ),
        ),
    ]
