# Generated by Django 4.2 on 2023-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0042_alter_union_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="union",
            name="name",
            field=models.CharField(
                help_text='Vi tilføjer automatisk "Coding Pirates" foran navnet når vi nævner det de fleste steder på siden.',
                max_length=200,
                verbose_name="Foreningens navn",
            ),
        ),
    ]
