# Generated by Django 4.2.3 on 2023-11-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0043_alter_union_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityinvite",
            name="price_in_dkk",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=500,
                help_text="Hvis det er et forløb / en sæsonaktivitet fratrækkes der automatisk 100 kr. til Coding Pirates Denmark pr. deltager. Denne pris overskriver prisen på aktiviteten. Angiv kun en pris hvis denne deltager skal have en anden pris end angivet i aktiviteten. Hvis prisen er under 100 kr. for et forløb / en sæsonaktivitet bliver barnet ikke medlem af foreningen og har ikke stemmeret til generalforsamlingen. Hvis der angives en anden pris, skal noten udfyldes med en begrundelse for denne prisoverskrivelse. Denne note er synlig for den inviterede deltager.",
                max_digits=10,
                null=True,
                verbose_name="Pris",
            ),
        ),
        migrations.AddField(
            model_name="activityinvite",
            name="price_note",
            field=models.TextField(blank=True, verbose_name="Note om særpris"),
        ),
    ]
