# Generated by Django 4.2.2 on 2023-08-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0043_alter_union_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="price_in_dkk",
            field=models.DecimalField(
                decimal_places=2,
                default=500,
                help_text="Hvis det er et forløb / en sæsonaktivitet fratrækkes der automatisk 100 kr. \n            til Coding Pirates Denmark pr. barn.",
                max_digits=10,
                verbose_name="Pris",
            ),
        ),
    ]
