# Generated by Django 4.2.2 on 2023-08-20 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0044_alter_activity_price_in_dkk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activitytype",
            field=models.ForeignKey(
                default="FORLØB",
                help_text="Angiv typen af aktivtet.\n        Brugere vil se Forløb og Arrangementer under Aktiviteter.\n        Medlemskab og Støttemedlemskab vil blive vist på separate sider.\n        Normalt vil det kun være sekretariatet der oprettet aktiviteter for medlemskaber.",
                on_delete=django.db.models.deletion.CASCADE,
                to="members.activitytype",
                verbose_name="Aktivitetstype",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="member_justified",
            field=models.BooleanField(
                default=True,
                help_text="Bestemmer om personerne bliver til medlem i forhold til DUF.\n        De fleste aktiviteter er forløb/sæsoner og medlemsberettiget. Hvis\n        du er i tvivl, så spørg på Slack i #medlemsssystem-support.",
                verbose_name="Aktiviteten gør personen til medlem",
            ),
        ),
    ]
