# Generated by Django 4.2 on 2023-09-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0044_activity_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="descriptiontext",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Beskrivelse"
            ),
        ),
    ]
