# Generated by Django 4.2 on 2024-03-29 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0045_activityinvite_extra_email_info_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["address__zipcode"],
                "permissions": (("view_all_departments", "Can view all Afdelinger"),),
                "verbose_name": "Afdeling",
                "verbose_name_plural": "Afdelinger",
            },
        ),
        migrations.AlterModelOptions(
            name="union",
            options={
                "ordering": ["name"],
                "permissions": (("view_all_unions", "Can view all Foreninger"),),
                "verbose_name": "Forening",
                "verbose_name_plural": "Foreninger",
            },
        ),
    ]
