# Generated by Django 4.2 on 2024-02-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0045_address_descriptiontext"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="dawa_category",
            field=models.CharField(
                blank=True, max_length=1, verbose_name="DAWA kategori"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="region",
            field=models.CharField(
                choices=[
                    ("Region Syddanmark", "Syddanmark"),
                    ("Region Hovedstaden", "Hovedstaden"),
                    ("Region Nordjylland", "Nordjylland"),
                    ("Region Midtjylland", "Midtjylland"),
                    ("Region Sjælland", "Sjælland"),
                    ("Online", "Online"),
                ],
                max_length=20,
                verbose_name="Region",
            ),
        ),
    ]
