# Generated by Django 4.2.2 on 2023-08-20 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0046_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_since",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 8, 20, 13, 55, 26, 196346, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Medlemskab start",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="price_in_dkk",
            field=models.DecimalField(
                decimal_places=2, default=75, max_digits=10, verbose_name="Pris"
            ),
        ),
    ]
