# Generated by Django 4.2 on 2024-03-29 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0045_activityinvite_extra_email_info_and_more"),
        ("members", "0046_address_dawa_category_alter_address_region"),
    ]

    operations = []
