# Generated by Django 4.2.11 on 2024-04-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0046_alter_department_options_alter_union_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="has_waiting_list",
            field=models.BooleanField(default=True, verbose_name="Brug af venteliste"),
        ),
    ]
