# Generated by Django 4.2.11 on 2024-08-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0047_department_has_waiting_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="union",
            name="gl_account",
            field=models.CharField(
                blank=True,
                help_text="Finanskontonummer i formatet 1234",
                max_length=4,
                verbose_name="Finanskonto:",
            ),
        ),
    ]
