# Generated by Django 4.2.2 on 2023-08-20 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0047_alter_member_member_since_alter_member_price_in_dkk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="price_in_dkk",
            field=models.DecimalField(
                decimal_places=2,
                default=500,
                help_text="Hvis det er et forløb / en sæsonaktivitet fratrækkes der automatisk 100 kr.\n            til Coding Pirates Denmark pr. barn.",
                max_digits=10,
                verbose_name="Pris",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="member_since",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Medlemskab start"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="member_until",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Medlemskab slut"
            ),
        ),
    ]
