# Generated by Django 4.2.11 on 2024-05-26 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0047_alter_emailitem_options_and_more"),
        ("members", "0047_department_has_waiting_list"),
    ]

    operations = []
