# Generated by Django 4.2.11 on 2024-08-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0048_union_gl_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="union",
            name="gl_account",
            field=models.CharField(
                blank=True,
                help_text="Kontonummer i formatet 1234",
                max_length=4,
                verbose_name="Finanskonto:",
            ),
        ),
    ]
