# Generated by Django 4.2.11 on 2024-04-07 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0046_alter_department_options_alter_union_options"),
        ("members", "0048_alter_address_dawa_overwrite"),
    ]

    operations = []
