# Generated by Django 4.2.2 on 2023-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0049_payment_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="union",
            name="membership_price_in_dkk",
            field=models.DecimalField(
                decimal_places=2,
                default=75,
                max_digits=10,
                verbose_name="Pris for medlemskab",
            ),
        ),
    ]
