# Generated by Django 4.2.11 on 2024-05-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0048_merge_20240526_1518"),
        ("members", "0049_merge_20240407_1605"),
    ]

    operations = []
