# Generated by Django 4.2.11 on 2024-05-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0050_merge_20240526_1736"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="region",
            field=models.CharField(
                choices=[
                    ("Region Syddanmark", "Syddanmark"),
                    ("Region Hovedstaden", "Hovedstaden"),
                    ("Region Nordjylland", "Nordjylland"),
                    ("Region Midtjylland", "Midtjylland"),
                    ("Region Sjælland", "Sjælland"),
                    ("Online", "Online"),
                    ("Andet", "Andet"),
                ],
                max_length=20,
                verbose_name="Region",
            ),
        ),
    ]
