# Generated by Django 4.2.11 on 2024-05-26 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0051_alter_address_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="members.address",
                verbose_name="Adresse",
            ),
        ),
    ]
