# Generated by Django 4.2.3 on 2023-09-24 11:36

from django.db import migrations, models
import members.models.member


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0051_alter_union_membership_price_in_dkk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_until",
            field=models.DateField(
                blank=True,
                default=members.models.member.end_of_year,
                null=True,
                verbose_name="Medlemskab slut",
            ),
        ),
    ]
