# Generated by Django 4.2.3 on 2023-09-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0052_alter_member_member_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityparticipant",
            name="price_in_dkk",
            field=models.DecimalField(
                decimal_places=2, default=425, max_digits=10, verbose_name="Pris"
            ),
        ),
    ]
