# Generated by Django 4.2.11 on 2024-06-17 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0052_alter_activity_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="visible",
            field=models.BooleanField(
                default=True,
                help_text="Vises i denne aktivtet. Kan bruges sammen med feltet 'Aktiviteten er synlig fra'",
                verbose_name="Vises denne aktivitet",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="visible_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Aktiviteten er synlig fra",
            ),
        ),
    ]
