# Generated by Django 4.2.11 on 2024-05-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0052_alter_activity_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailitem",
            options={
                "ordering": ["-created_dtm"],
                "verbose_name": "Afsendt email",
                "verbose_name_plural": "Afsendte emails",
            },
        ),
    ]
