# Generated by Django 4.2.11 on 2024-06-01 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0052_alter_activity_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="visible_from",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Aktiviteten er synlig fra",
            ),
        ),
    ]
