# Generated by Django 4.2.11 on 2024-05-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0053_activityparticipant_price_in_dkk"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Betalt"),
        ),
    ]
