# Generated by Django 4.2.11 on 2024-06-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0053_activity_visible_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="visible",
            field=models.BooleanField(
                default=True,
                help_text="Vises i denne aktivtet. Kan bruges sammen med feltet 'Aktiviteten er synlig fra'",
                verbose_name="Vises denne aktivitet",
            ),
        ),
    ]
