# Generated by Django 4.2.11 on 2024-06-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0053_activity_visible_activity_visible_from"),
        ("members", "0053_alter_emailitem_options"),
    ]

    operations = []
