# Generated by Django 4.2.14 on 2024-07-21 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0054_merge_20240617_2150"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailitem",
            name="activity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.activity",
            ),
        ),
    ]
