# Generated by Django 4.2.11 on 2024-08-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0054_merge_20240617_2150"),
    ]

    operations = [
        migrations.RenameField(
            model_name="union",
            old_name="union_email",
            new_name="email",
        ),
    ]
