# Generated by Django 4.2.16 on 2024-10-27 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0055_rename_union_email_union_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityinvite",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="members.activity",
                verbose_name="Aktivitet",
            ),
        ),
    ]
