# Generated by Django 4.2.11 on 2024-08-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0054_member_paid_at"),
        ("members", "0055_rename_union_email_union_email"),
    ]

    operations = []
