# Generated by Django 4.2.11 on 2024-08-31 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0056_merge_20240831_1421"),
    ]

    operations = [
        migrations.AddField(
            model_name="union",
            name="memberships_allowed_at",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                help_text="Hvis feltet er tomt, vil det ikke være tilladt at være medlem af foreningen.",
                null=True,
                verbose_name="Dato hvor medlemskaber er tilladt fra",
            ),
        ),
    ]
