# Generated by Django 4.2.11 on 2024-11-11 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0057_union_memberships_allowed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activityparticipant",
            name="contact_visible",
        ),
    ]
