# Generated by Django 4.2.16 on 2024-10-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0057_municipality"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="municipality",
            options={
                "ordering": ["name"],
                "verbose_name": "Kommune",
                "verbose_name_plural": "Kommuner",
            },
        ),
        migrations.RemoveField(
            model_name="municipality",
            name="email",
        ),
        migrations.RemoveField(
            model_name="municipality",
            name="municipality",
        ),
        migrations.AddField(
            model_name="municipality",
            name="dawa_id",
            field=models.CharField(blank=True, max_length=200, verbose_name="DAWA id"),
        ),
        migrations.AddField(
            model_name="municipality",
            name="name",
            field=models.CharField(default="", max_length=255, verbose_name="Navn"),
        ),
    ]
