# Generated by Django 4.2.11 on 2024-11-13 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0057_municipality"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="union",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("view_all_unions", "Can view all Foreninger"),
                    ("showledgeraccount", "Show General Ledger Account"),
                ),
                "verbose_name": "Forening",
                "verbose_name_plural": "Foreninger",
            },
        ),
        migrations.AddField(
            model_name="union",
            name="gl_account",
            field=models.CharField(
                blank=True,
                help_text="Kontonummer i formatet 1234",
                max_length=4,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Indtast kontonummer i det rigtige format.",
                        regex="^[0-9]{4}",
                    )
                ],
                verbose_name="Finanskonto:",
            ),
        ),
    ]
