# Generated by Django 4.2.11 on 2024-11-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0058_alter_municipality_options_remove_municipality_email_and_more",
        ),
        ("members", "0058_alter_union_options_union_gl_account"),
    ]

    operations = []
