# Generated by Django 4.2.16 on 2024-11-11 21:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "members",
            "0058_alter_municipality_options_remove_municipality_email_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="municipality",
        ),
    ]
