# Generated by Django 1.9.1 on 2016-01-11 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0059_auto_20160107_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Oprettet'),
        ),
    ]
