# Generated by Django 4.2.11 on 2024-11-13 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0059_merge_20241113_2111"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="union",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("view_all_unions", "Can view all Foreninger"),
                    ("show_ledger_account", "Show General Ledger Account"),
                ),
                "verbose_name": "Forening",
                "verbose_name_plural": "Foreninger",
            },
        ),
    ]
