# Generated by Django 4.2.11 on 2024-12-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0060_alter_union_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activityparticipant",
            name="contact_visible",
        ),
    ]
