# Generated by Django 4.2.16 on 2024-12-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0060_alter_union_options"),
        ("members", "0060_person_municipality"),
    ]

    operations = []
