# Generated by Django 4.2.11 on 2024-11-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0047_volunteerrequest_volunteerrequestdepartment_and_more"),
        ("members", "0060_alter_union_options"),
    ]

    operations = []
