# Generated by Django 1.9.1 on 2016-01-15 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0060_auto_20160111_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='dont_send_mails',
            field=models.BooleanField(default=False, verbose_name='Vil ikke kontaktes'),
        ),
    ]
