# Generated by Django 4.2.11 on 2024-12-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0061_remove_activityparticipant_contact_visible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="city",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="dawa_id",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="door",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="floor",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="housenumber",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="placename",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="streetname",
        ),
        migrations.RemoveField(
            model_name="activity",
            name="zipcode",
        ),
    ]
