# Generated by Django 4.2.11 on 2024-12-20 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0061_merge_20241125_1626"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.activity",
                verbose_name="Aktivitet",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="end_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Start dato"
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="start_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Start dato"
            ),
        ),
    ]
