# Generated by Django 4.2.11 on 2024-12-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0062_volunteer_activity_volunteer_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="end_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Slut"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="start_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Start"
            ),
        ),
    ]
