# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0062_auto_20160115_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuserinformation',
            name='departments',
            field=models.ManyToManyField(related_name='departments', to='members.Department'),
        ),
        migrations.AlterField(
            model_name='adminuserinformation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department', to='members.Department'),
        ),
    ]
