# Generated by Django 4.2.16 on 2024-12-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0061_merge_20241229_1052"),
        ("members", "0062_remove_activity_city_remove_activity_dawa_id_and_more"),
    ]

    operations = []
