# Generated by Django 1.9.1 on 2016-01-16 08:56
from __future__ import unicode_literals

from django.db import migrations

def make_many_departments(apps, schema_editor):
    """
    adds the single department to the manytomany departments
    """

    AdminUserInformation = apps.get_model('members', 'AdminUserInformation')

    for adminuserinformation in AdminUserInformation.objects.all():
        adminuserinformation.departments.add(adminuserinformation.department)

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0063_auto_20160116_0955'),
    ]

    operations = [
        migrations.RunPython(make_many_departments),
    ]
