# Generated by Django 4.2.11 on 2025-01-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0058_remove_activityparticipant_contact_visible"),
        ("members", "0063_merge_20241229_1529"),
    ]

    operations = []
