# Generated by Django 4.2.11 on 2025-01-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0057_union_memberships_allowed_at"),
        ("members", "0063_merge_20241229_1529"),
    ]

    operations = []
