# Generated by Django 4.2.17 on 2025-01-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0063_merge_20241229_1529"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="anonymized",
            field=models.BooleanField(default=False, verbose_name="Anonymiseret"),
        ),
        migrations.AddField(
            model_name="person",
            name="anonymized",
            field=models.BooleanField(default=False, verbose_name="Anonymiseret"),
        ),
    ]
