# Generated by Django 4.2.11 on 2024-12-20 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0063_alter_volunteer_end_date_alter_volunteer_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerrequestdepartment",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="members.activity",
                verbose_name="Aktivitet",
            ),
        ),
    ]
