# Generated by Django 4.2.11 on 2024-12-27 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0064_volunteerrequestdepartment_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="added_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Oprettet"
            ),
        ),
    ]
