# Generated by Django 1.9.1 on 2016-01-16 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0064_auto_20160116_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuserinformation',
            name='department',
        ),
        migrations.AlterField(
            model_name='adminuserinformation',
            name='departments',
            field=models.ManyToManyField(to='members.Department'),
        ),
    ]
