# Generated by Django 4.2.17 on 2024-12-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0063_merge_20241229_1529"),
        ("members", "0065_alter_volunteer_added_at"),
    ]

    operations = []
