# Generated by Django 1.9.1 on 2016-02-06 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0065_auto_20160116_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='family',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='person',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['department__zipcode', 'start_date'], 'verbose_name': 'Aktivitet', 'verbose_name_plural': 'Aktiviteter'},
        ),
        migrations.AlterModelOptions(
            name='activityinvite',
            options={'verbose_name': 'Invitation', 'verbose_name_plural': 'Invitationer'},
        ),
        migrations.AlterModelOptions(
            name='activityparticipant',
            options={'verbose_name': 'Deltager', 'verbose_name_plural': 'Deltagere'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['zipcode'], 'verbose_name': 'Afdeling', 'verbose_name_plural': 'Afdelinger'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'permissions': (('view_family_unique', 'Can view family UUID field (password) - gives access to address'),), 'verbose_name': 'Familie', 'verbose_name_plural': 'Familier'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['is_active', 'member_since'], 'verbose_name': 'Medlem', 'verbose_name_plural': 'Medlemmer'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['added'], 'permissions': (('view_full_address', 'Can view persons full address + phonenumber + email'),), 'verbose_name': 'Person', 'verbose_name_plural': 'Personer'},
        ),
        migrations.AlterModelOptions(
            name='waitinglist',
            options={'ordering': ['on_waiting_list_since'], 'verbose_name': 'På venteliste', 'verbose_name_plural': 'På ventelister'},
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
