# Generated by Django 1.9.1 on 2016-02-07 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0067_auto_20160207_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='closed_dtm',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Lukket'),
        ),
    ]
