# Generated by Django 1.9.1 on 2016-02-15 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0068_department_closed_dtm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['added'], 'permissions': (('view_full_address', 'Can view persons full address + phonenumber + email'), ('view_all_persons', 'Can view persons not related to department')), 'verbose_name': 'Person', 'verbose_name_plural': 'Personer'},
        ),
    ]
