# Generated by Django 1.9.1 on 2016-07-09 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0069_auto_20160215_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Union',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Foreningens navn')),
                ('chairman', models.CharField(blank=True, max_length=200, verbose_name='Formand')),
                ('chairman_email', models.EmailField(blank=True, max_length=254, verbose_name='Formandens email')),
                ('second_chair', models.CharField(blank=True, max_length=200, verbose_name='Næstformand')),
                ('second_chair_email', models.EmailField(blank=True, max_length=254, verbose_name='Næstformandens email')),
                ('cashier', models.CharField(blank=True, max_length=200, verbose_name='Kassere')),
                ('cashier_email', models.EmailField(blank=True, max_length=254, verbose_name='Kasserens email')),
                ('union_email', models.EmailField(blank=True, max_length=254, verbose_name='Foreningens email')),
                ('statues', models.URLField(blank=True, verbose_name='Link til gældende vedtægter')),
                ('founded', models.DateField(blank=True, verbose_name='Stiftet')),
                ('region', models.CharField(choices=[('S', 'Sjælland'), ('J', 'Jylland'), ('F', 'Fyn'), ('Ø', 'Øer')], max_length=1, verbose_name='region')),
                ('placename', models.CharField(blank=True, max_length=200, verbose_name='Stednavn')),
                ('zipcode', models.CharField(max_length=10, verbose_name='Postnummer')),
                ('city', models.CharField(max_length=200, verbose_name='By')),
                ('streetname', models.CharField(max_length=200, verbose_name='Vejnavn')),
                ('housenumber', models.CharField(max_length=10, verbose_name='Husnummer')),
                ('floor', models.CharField(blank=True, max_length=10, verbose_name='Etage')),
                ('door', models.CharField(blank=True, max_length=10, verbose_name='Dør')),
                ('boardMembers', models.TextField(blank=True, verbose_name='Meninge medlemmer')),
            ],
            options={
                'verbose_name_plural': 'Foreninger',
                'verbose_name': 'Forening',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='isVisible',
            field=models.BooleanField(default=True, verbose_name='Kan ses på afdelingssiden'),
        ),
        migrations.AddField(
            model_name='department',
            name='website',
            field=models.URLField(blank=True, verbose_name='Hjemmeside'),
        ),
        migrations.AddField(
            model_name='department',
            name='union',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.Union'),
            preserve_default=False,
        ),
    ]
