# Generated by Django 4.2.18 on 2025-02-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0065_alter_person_options"),
        ("members", "0069_alter_person_name"),
    ]

    operations = []
