# Generated by Django 1.9.1 on 2016-03-22 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0069_auto_20160215_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='membertype',
            field=models.CharField(choices=[('PA', 'Forælder'), ('GU', 'Værge'), ('CH', 'Barn'), ('VO', 'Frivillig'), ('NA', 'Anden')], default='PA', max_length=2, verbose_name='Type'),
        ),
    ]
