# Generated by Django 4.2.11 on 2025-02-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0064_merge_20250112_1147"),
        ("members", "0070_merge_20250223_1450"),
    ]

    operations = []
