# Generated by Django 1.9.1 on 2016-07-09 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0070_auto_20160710_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Union', verbose_name='Forening'),
        ),
    ]
