# Generated by Django 4.2.17 on 2025-03-09 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("members", "0070_merge_20250223_1450"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Hvornår er denne privatlivspolitik gældende fra ?",
                        null=True,
                        verbose_name="Gældende fra",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titel")),
                (
                    "text",
                    models.TextField(
                        help_text="Tekst for privatlivspolitik",
                        verbose_name="Privatlivspolitik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Privatlivspolitik",
                "verbose_name_plural": "Privatlivspolitikker",
                "ordering": ["-released_at"],
            },
        ),
        migrations.AddField(
            model_name="person",
            name="consent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Samtykke dato"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="consent_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="person_consent_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="user",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="person_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="consent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="members.consent",
            ),
        ),
    ]
