# Generated by Django 4.2.11 on 2025-03-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0071_merge_20250223_1523"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="price_in_dkk",
            field=models.DecimalField(
                decimal_places=2,
                default=500,
                help_text="Hvis det er et forløb / en sæsonaktivitet fratrækkes der automatisk 100 kr. til Coding Pirates Denmark pr. barn.",
                max_digits=10,
                verbose_name="Pris",
            ),
        ),
        migrations.AlterField(
            model_name="activityinvite",
            name="price_in_dkk",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hvis det er et forløb / en sæsonaktivitet fratrækkes der automatisk 100 kr. til Coding Pirates Denmark pr. deltager. Denne pris overskriver prisen på aktiviteten. Angiv kun en pris hvis denne deltager skal have en anden pris end angivet i aktiviteten. Hvis der angives en anden pris, skal noten udfyldes med en begrundelse for denne prisoverskrivelse. Denne note er synlig for den inviterede deltager.",
                max_digits=10,
                null=True,
                verbose_name="Pris",
            ),
        ),
    ]
