# Generated by Django 4.2.20 on 2025-04-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0073_alter_person_consent_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="referer",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Hvor hørte du om Coding Pirates?",
            ),
        ),
    ]
