# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0073_auto_20160429_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start'),
        ),
    ]
