# Generated by Django 4.2.18 on 2025-04-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0073_alter_activity_member_justified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="member_justified",
        ),
    ]
