# Generated by Django 4.2.21 on 2025-06-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0074_family_referer"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymizationCandidate",
            fields=[],
            options={
                "verbose_name": "Anonymiserings kandidat",
                "verbose_name_plural": "Anonymiserings kandidater",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("members.person",),
        ),
    ]
