# Generated by Django 4.2.20 on 2025-04-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0073_alter_person_consent_by"),
        ("members", "0074_remove_activity_member_justified"),
    ]

    operations = []
