# Generated by Django 1.9.1 on 2016-04-30 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0074_auto_20160429_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='approved',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Godkendt af afdelingsleder'),
        ),
    ]
