# Generated by Django 4.2.17 on 2025-06-21 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0074_family_referer"),
    ]

    operations = [
        migrations.AddField(
            model_name="union",
            name="cvr",
            field=models.CharField(
                blank=True,
                help_text="CVR-nummer i formatet 12345678",
                max_length=8,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Indtast CVR-nummer i det rigtige format.",
                        regex="^[0-9]{8}$",
                    )
                ],
                verbose_name="CVR-nummer",
            ),
        ),
    ]
