# Generated by Django 4.2.20 on 2025-05-30 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0074_family_referer"),
        ("members", "0075_merge_20250415_0041"),
    ]

    operations = []
