# Generated by Django 1.9.1 on 2016-04-30 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0075_auto_20160430_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='member',
            new_name='person',
        ),
    ]
