# Generated by Django 4.2.20 on 2025-06-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0076_merge_0074_family_referer_0075_merge_20250415_0041"),
    ]

    operations = [
        migrations.AddField(
            model_name="union",
            name="new_membership_model_activated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Bemærk: Aktiverer du den nye medlemstabel for en forening kan det ikke ændres tilbage! Det har betydning for flere ting, og vi låser derfor feltet. Står der ikke en dato i feltet, er den nye model ikke aktiv. Står der en dato i fremtiden er den heller ikke aktiv endnu, og kan ændres. Står der en dato i fortiden er den aktiv fra og med den dato.",
                null=True,
                verbose_name="Ny medlemskabsmodel aktiveret",
            ),
        ),
    ]
