# Generated by Django 1.9.1 on 2016-05-06 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0076_auto_20160430_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='approved',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Godkendt af afdelingsleder'),
        ),
    ]
