# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-08 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0077_auto_20160506_1714'),
        ('members', '0072_auto_20160710_2226'),
    ]

    operations = [
    ]
