# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-08 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0078_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Længdegrad'),
        ),
        migrations.AddField(
            model_name='department',
            name='longtitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9, verbose_name='Breddegrad'),
        ),
    ]
