# Generated by Django 4.2.20 on 2025-06-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0075_union_cvr"),
        (
            "members",
            "0077_union_new_membership_model_activated_at_squashed_0079_alter_union_new_membership_model_activated_at",
        ),
    ]

    operations = []
