# Generated by Django 4.2.20 on 2025-06-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0075_anonymizationcandidate"),
        ("members", "0080_merge_20250621_1619"),
    ]

    operations = []
