# Generated by Django 4.2.22 on 2025-06-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0081_merge_20250621_1649"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="union",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("view_all_unions", "Can view all Foreninger"),
                    ("show_ledger_account", "Show General Ledger Account"),
                    ("show_new_membership_model", "Show New Membership Model"),
                ),
                "verbose_name": "Forening",
                "verbose_name_plural": "Foreninger",
            },
        ),
    ]
