# Generated by Django 1.9.1 on 2016-10-09 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0081_auto_20161008_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='onMap',
            field=models.BooleanField(default=True, verbose_name='Skal den være på kortet?'),
        ),
    ]
