# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-09 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0082_department_onmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='isOpen',
            field=models.BooleanField(default=False, verbose_name='Er afdelingen åben'),
        ),
    ]
