# Generated by Django 4.2.22 on 2025-07-27 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0082_alter_union_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Region Syddanmark", "Syddanmark"),
                    ("Region Hovedstaden", "Hovedstaden"),
                    ("Region Nordjylland", "Nordjylland"),
                    ("Region Midtjylland", "Midtjylland"),
                    ("Region Sjælland", "Sjælland"),
                    ("Andet", "Andet"),
                ],
                default=None,
                max_length=20,
                null=True,
                verbose_name="Region",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        '^(?!.*[:;,"[\\]{}*&^%$#@!_+=\\/\\\\\\\\<>|])\\S+\\s+\\S+.*$',
                        message="Indtast et gyldigt navn bestående af fornavn og minimum et efternavn.",
                    )
                ],
                verbose_name="Navn",
            ),
        ),
    ]
