# Generated by Django 5.0.14 on 2025-06-27 20:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0082_alter_union_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.RegexValidator(
                        '^(?!.*[:;,"[\\]{}*&^%$#@!_+=\\/\\\\\\\\<>|])\\S+\\s+\\S+.*$',
                        message="Indtast et gyldigt navn bestående af fornavn og minimum et efternavn.",
                    )
                ],
                verbose_name="Navn",
            ),
        ),
    ]
