# Generated by Django 5.2.6 on 2025-11-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0083_person_region_alter_person_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="temp_anonymizing_warning_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Anonymiseringsadvarsel sendt"
            ),
        ),
    ]
