# Generated by Django 5.2.6 on 2025-11-14 11:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0083_person_region_alter_person_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="members.activity",
                verbose_name="Aktivitet",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="end_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Slutdato"
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="start_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Startdato"
            ),
        ),
        migrations.CreateModel(
            name="VolunteerRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Navn"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "age",
                    models.IntegerField(blank=True, null=True, verbose_name="Alder"),
                ),
                (
                    "zip",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Postnummer"
                    ),
                ),
                (
                    "info_reference",
                    models.TextField(
                        help_text="Hvor har du hørt om Coding Pirates (SoMe, Facebook, Instagram, LinkedIn, en ven, en kollega, etc) ?",
                        max_length=200,
                        verbose_name="Reference",
                    ),
                ),
                (
                    "info_whishes",
                    models.TextField(
                        help_text="Hvilke ønsker har du til at være frivillig hos Coding Pirates ?",
                        max_length=1024,
                        verbose_name="Ønsker",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Tidspunkt for oprettelse",
                        verbose_name="Oprettet",
                    ),
                ),
                (
                    "finished",
                    models.DateTimeField(
                        blank=True,
                        help_text="Tidspunkt for færdigbehandling",
                        null=True,
                        verbose_name="Færdigbehandlet",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frivillig anmodning",
                "verbose_name_plural": "Frivillig anmodninger",
            },
        ),
        migrations.CreateModel(
            name="VolunteerRequestItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Tidspunkt for oprettelse",
                        verbose_name="Oprettet",
                    ),
                ),
                (
                    "finished",
                    models.DateTimeField(
                        blank=True,
                        help_text="Tidspunkt for færdigbehandling",
                        null=True,
                        verbose_name="Færdigbehandlet",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Ny anmodning"),
                            ("REJECTED", "Afvist af afdeling"),
                            ("NOT_INTERESTED", "Person er ikke interesseret"),
                            ("WAITING", "Venter på at personen oprettes i systemet"),
                            ("ACTIVE", "Aktiv"),
                        ],
                        default="NEW",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.activity",
                        verbose_name="Aktivitet",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.department",
                        verbose_name="Afdeling",
                    ),
                ),
                (
                    "volunteer_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="members.volunteerrequest",
                        verbose_name="Frivillig Anmodning",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frivillig anmodning for en afdeling",
                "verbose_name_plural": "Frivillig anmodninger for afdelinger",
            },
        ),
        migrations.AddConstraint(
            model_name="volunteerrequest",
            constraint=models.UniqueConstraint(
                models.F("token"), name="unique appversion"
            ),
        ),
    ]
