# Generated by Django 5.2.4 on 2025-09-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0066_merge_20241231_1725"),
        ("members", "0083_alter_person_name"),
    ]

    operations = []
