# Generated by Django 1.9.1 on 2016-10-09 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0083_department_isopen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='isOpen',
        ),
        migrations.AddField(
            model_name='department',
            name='isOpening',
            field=models.BooleanField(default=False, verbose_name='Er afdelingen under opstart'),
        ),
    ]
