# Generated by Django 5.2.6 on 2025-11-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0084_family_temp_anonymizing_warning_sent_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="family",
            old_name="temp_anonymizing_warning_sent_at",
            new_name="temp_anonymization_warning_sent_at",
        ),
    ]
