# Generated by Django 5.2.6 on 2025-11-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0084_volunteer_activity_volunteer_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="info_reference",
            field=models.TextField(
                blank=True,
                help_text="Hvor har du hørt om Coding Pirates (SoMe, Facebook, Instagram, LinkedIn, en ven, en kollega, etc)?",
                max_length=200,
                null=True,
                verbose_name="Reference",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="info_whishes",
            field=models.TextField(
                blank=True,
                help_text="Hvilke ønsker har du til at være frivillig hos Coding Pirates?",
                max_length=1024,
                null=True,
                verbose_name="Ønsker",
            ),
        ),
    ]
