# Generated by Django 4.2.20 on 2025-09-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0084_merge_0066_merge_20241231_1725_0083_alter_person_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerrequestdepartment",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Ny anmodning"),
                    (2, "Afvist af afdeling"),
                    (3, "Person er ikke interesseret"),
                    (4, "Venter på at personen oprettes i systemet"),
                    (5, "Aktiv"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
    ]
