# Generated by Django 5.2.6 on 2025-11-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "members",
            "0085_rename_temp_anonymizing_warning_sent_at_family_temp_anonymization_warning_sent_at",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="family",
            old_name="last_visit_dtm",
            new_name="last_visit_at",
        ),
    ]
