# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0085_person_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Noter'),
        ),
    ]
