# Generated by Django 5.2.6 on 2026-01-03 14:16

import django.db.models.deletion
import members.models.department
from django.db import migrations, models


def create_initial_activity_modes(apps, schema_editor):
    ActivityMode = apps.get_model("members", "ActivityMode")
    ActivityMode.objects.create(
        code="SÆSON", name="Sæson", description="Kun sæson/forløb"
    )
    ActivityMode.objects.create(
        code="ARRANGEMENT", name="Arrangement", description="Kun arrangementer"
    )
    ActivityMode.objects.create(
        code="DELSÆSON",
        name="Delsæson",
        description="Del-sæson (reduceret sæsonbidrag)",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0086_rename_last_visit_dtm_family_last_visit_at"),
    ]

    def set_season_fee_default(apps, schema_editor):
        Activity = apps.get_model("members", "Activity")
        Activity.objects.filter(season_fee__isnull=True).update(season_fee=0)

    operations = [
        migrations.CreateModel(
            name="ActivityMode",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Aktivitetsform",
                "verbose_name_plural": "Aktivitetsformer",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="activity",
            name="season_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Standard er 150 kr for sæson/forløb, 0 kr for Arrangementer og Støttemedlemskaber.<br>Beregnes automatisk ved oprettelse af aktiviteten.",
                max_digits=7,
                null=True,
                verbose_name="Sæsonbidrag til Coding Pirates Denmark",
            ),
        ),
        migrations.RunPython(set_season_fee_default),
        migrations.AddField(
            model_name="activity",
            name="season_fee_change_reason",
            field=models.CharField(
                blank=True,
                help_text="Påkrævet hvis sæsonbidrag ændres fra standard.",
                max_length=255,
                verbose_name="Begrundelse for ændring af sæsonbidrag",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="activitytype",
            field=models.ForeignKey(
                default="FORLØB",
                help_text="Angiv typen af aktivitet. Brugere vil se Forløb og Arrangementer under Aktiviteter.<br>Medlemskab og Støttemedlemskab vil blive vist på separate sider.<br>Medlemskab bliver oprettet automatisk af systemet.",
                on_delete=django.db.models.deletion.CASCADE,
                to="members.activitytype",
                verbose_name="Aktivitetstype",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="activity_mode",
            field=models.ForeignKey(
                blank=True,
                default=members.models.department.get_default_activity_mode,
                help_text="Angiv hvilken type aktiviteter afdelingen tilbyder",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="members.activitymode",
                verbose_name="Aktivitetsform",
            ),
        ),
        migrations.RunPython(create_initial_activity_modes),
    ]
