# Generated by Django 5.2.6 on 2026-01-18 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0086_rename_last_visit_dtm_family_last_visit_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackInvitationSetup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invite_url",
                    models.URLField(blank=True, verbose_name="Slack Invite URL"),
                ),
                (
                    "emails",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of allowed email addresses.",
                        verbose_name="Allowed Email Addresses",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slack_invite_setups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Invitation Setup",
                "verbose_name_plural": "Slack Invitation Setup",
            },
        ),
        migrations.CreateModel(
            name="SlackInviteLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("purpose", models.CharField(blank=True, max_length=255)),
                ("invite_url", models.URLField(blank=True, verbose_name="Invite URL")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Created"),
                            (2, "Invite used"),
                            (3, "URL failed/email sent"),
                        ],
                        default=1,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slack_invite_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Slack Invite Log",
                "verbose_name_plural": "Slack Invite Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SlackLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slack_user_id",
                    models.CharField(
                        help_text="Slack user ID for the invitee", max_length=64
                    ),
                ),
                (
                    "slack_email",
                    models.EmailField(
                        help_text="Email address of the invitee", max_length=254
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action taken, e.g. 'approved'", max_length=32
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "details",
                    models.TextField(
                        blank=True, help_text="Additional details or Slack API response"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("can_approve_slack_invites", "Can approve Slack invitations"),
                ),
            },
        ),
    ]
