# Generated by Django 5.2.10 on 2026-01-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0087_activitymode_activity_season_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityinvite",
            name="reminder_sent_at",
            field=models.DateField(blank=True, null=True, verbose_name="Påmindet"),
        ),
    ]
