# Generated by Django 5.2.8 on 2026-01-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0087_slackinvitationsetup_slackinvitelog_slacklog"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackinvitationsetup",
            name="admin_password",
            field=models.CharField(
                blank=True,
                help_text="Password for the Slack admin user (store securely).",
                max_length=256,
                verbose_name="Slack Admin Password",
            ),
        ),
        migrations.AddField(
            model_name="slackinvitationsetup",
            name="admin_username",
            field=models.EmailField(
                blank=True,
                help_text="Email address of the Slack admin user to log in as.",
                max_length=254,
                verbose_name="Slack Admin Username",
            ),
        ),
        migrations.AlterField(
            model_name="slackinvitationsetup",
            name="emails",
            field=models.TextField(
                blank=True,
                help_text="Space-separated list of allowed email addresses.",
                verbose_name="Allowed Email Addresses",
            ),
        ),
        migrations.AlterField(
            model_name="slackinvitationsetup",
            name="invite_url",
            field=models.URLField(
                blank=True,
                help_text="URL for Slack admin invite page, e.g. https://yourteam.slack.com/sign_in_with_password?redir=%2Fadmin%2Finvites",
                verbose_name="Slack Admin Invite URL",
            ),
        ),
    ]
