# Generated by Django 1.9.1 on 2016-10-16 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0087_auto_20161016_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='union',
            name='secratary_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Sekratærens email'),
        ),
        migrations.AlterField(
            model_name='union',
            name='cashier_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Kasserens email'),
        ),
    ]
