# Generated by Django 5.2.8 on 2026-01-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0088_slackinvitationsetup_admin_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slackinvitationsetup",
            name="admin_password",
        ),
        migrations.AddField(
            model_name="slackinvitationsetup",
            name="admin_password_encrypted",
            field=models.BinaryField(
                blank=True,
                help_text="Password for the Slack admin user (encrypted).",
                null=True,
                verbose_name="Slack Admin Password (Encrypted)",
            ),
        ),
        migrations.AlterField(
            model_name="slackinvitationsetup",
            name="emails",
            field=models.TextField(
                blank=True,
                help_text="Space-separated list of allowed email addresses.",
                verbose_name="Notifikations Email Addresser",
            ),
        ),
    ]
