# Generated by Django 5.2.8 on 2026-01-18 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0089_remove_slackinvitationsetup_admin_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slackinvitelog",
            name="name",
        ),
    ]
