# Generated by Django 5.2.8 on 2026-06-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0089_volunteerrequest_allow_cpdk_contact"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["added_at"],
                "permissions": (
                    (
                        "view_full_address",
                        "Can view persons full address + phonenumber + email",
                    ),
                    ("view_all_persons", "Can view persons not related to department"),
                    ("anonymize_persons", "Can anonymize persons"),
                    (
                        "view_consent_information",
                        "Can view consent information for persons",
                    ),
                    ("see_contacts_shared_with_cpdk", "See contacts shared with CPDK"),
                    (
                        "see_contacts_shared_with_other",
                        "See contacts shared with other",
                    ),
                ),
                "verbose_name": "Person",
                "verbose_name_plural": "Personer",
            },
        ),
    ]
