# Generated by Django 5.2.8 on 2026-01-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0090_remove_slackinvitelog_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slackinvitelog",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_approve_slack_invites", "Can approve Slack invites")
                ],
                "verbose_name": "Slack Invite Log",
                "verbose_name_plural": "Slack Invite Logs",
            },
        ),
    ]
