# Generated by Django 1.9.1 on 2017-01-21 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0091_zipcoderegion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='approved',
        ),
    ]
