# Generated by Django 5.2.8 on 2026-01-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0087_activitymode_activity_season_fee_and_more"),
        ("members", "0091_alter_slackinvitelog_options"),
    ]

    operations = []
