# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-07 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Waitinglist = apps.get_model("members", "Waitinglist")
    for i in Waitinglist.objects.all():
        i.added_dtm = i.on_waiting_list_since
        i.save()

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0092_remove_volunteer_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatisticsDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2017, 6, 7, 22, 40, 59, 8570), verbose_name='Kørsels tidspunkt')),
                ('active_activities', models.IntegerField(default=0, verbose_name='Aktiviteter der er igang')),
                ('activities', models.IntegerField(default=0, verbose_name='Aktiviteter i alt')),
                ('current_activity_participants', models.IntegerField(default=0, verbose_name='Deltagere på aktiviteter')),
                ('current_activity_participants_age_avg', models.FloatField(default=0, verbose_name='Deltagere på aktiviteter gennemsnit alder')),
                ('current_activity_participants_age_min', models.FloatField(default=0, verbose_name='Deltagere på aktiviteter yngste alder')),
                ('current_activity_participants_age_max', models.FloatField(default=0, verbose_name='Deltagere på aktiviteter ældste alder')),
                ('activity_participants', models.IntegerField(default=0, verbose_name='Deltagere på aktiviteter over al tid')),
                ('members', models.IntegerField(default=0, verbose_name='Medlemmer')),
                ('waitinglist', models.IntegerField(default=0, verbose_name='Venteliste')),
                ('waitingtime', models.DurationField(default=0, verbose_name='Ventetid')),
                ('payments', models.IntegerField(default=0, verbose_name='Betalinger')),
                ('volunteers_male', models.IntegerField(default=0, verbose_name='Frivillige Mænd')),
                ('volunteers_female', models.IntegerField(default=0, verbose_name='Frivillige Kvinder')),
                ('volunteers', models.IntegerField(default=0, verbose_name='Frivillige')),
                ('volunteers_age_avg', models.FloatField(default=0, verbose_name='Frivillige gennemsnit alder')),
                ('volunteers_age_min', models.FloatField(default=0, verbose_name='Frivillige yngste alder')),
                ('volunteers_age_max', models.FloatField(default=0, verbose_name='Frivillige ældste alder')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Department')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStatisticsGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2017, 6, 7, 22, 40, 59, 10570), verbose_name='Kørsels tidspunkt')),
                ('persons', models.IntegerField(default=0, verbose_name='Personer')),
                ('children_male', models.IntegerField(default=0, verbose_name='Børn Drenge')),
                ('children_female', models.IntegerField(default=0, verbose_name='Børn Piger')),
                ('children', models.IntegerField(default=0, verbose_name='Børn')),
                ('volunteers_male', models.IntegerField(default=0, verbose_name='Frivillige Mænd')),
                ('volunteers_female', models.IntegerField(default=0, verbose_name='Frivillige Kvinder')),
                ('volunteers', models.IntegerField(default=0, verbose_name='Frivillige')),
                ('departments', models.IntegerField(default=0, verbose_name='Afdelinger')),
                ('unions', models.IntegerField(default=0, verbose_name='Lokalforeninger')),
                ('waitinglist', models.IntegerField(default=0, verbose_name='Personer på venteliste')),
                ('family_visits', models.IntegerField(default=0, verbose_name='Profilsider besøgt foregående 24 timer')),
                ('dead_profiles', models.IntegerField(default=0, verbose_name='Profilsider efterladt over et år')),
                ('current_activity_participants', models.IntegerField(default=0, verbose_name='Deltagere på aktiviteter')),
                ('activity_participants', models.IntegerField(default=0, verbose_name='Deltagere på aktiviteter over al tid')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStatisticsRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2017, 6, 7, 22, 40, 59, 10070), verbose_name='Kørsels tidspunkt')),
                ('region', models.CharField(choices=[('DK01', 'Hovedstaden'), ('DK02', 'Sjælland'), ('DK03', 'Syddanmark'), ('DK04', 'Midtjylland'), ('DK05', 'Nordjylland')], max_length=4, verbose_name='Region')),
                ('departments', models.IntegerField(default=0, verbose_name='Afdelinger')),
                ('unions', models.IntegerField(default=0, verbose_name='Lokalforeninger')),
                ('active_activities', models.IntegerField(default=0, verbose_name='Aktiviteter der er igang')),
                ('activities', models.IntegerField(default=0, verbose_name='Aktiviteter i alt')),
                ('current_activity_participants', models.IntegerField(default=0, verbose_name='Deltagere på aktiviteter')),
                ('current_activity_participants_age_avg', models.FloatField(default=0, verbose_name='Deltagere på aktiviteter gennemsnit alder')),
                ('current_activity_participants_age_min', models.FloatField(default=0, verbose_name='Deltagere på aktiviteter yngste alder')),
                ('current_activity_participants_age_max', models.FloatField(default=0, verbose_name='Deltagere på aktiviteter ældste alder')),
                ('activity_participants', models.IntegerField(default=0, verbose_name='Deltagere på aktiviteter over al tid')),
                ('members', models.IntegerField(default=0, verbose_name='Medlemmer')),
                ('waitinglist', models.IntegerField(default=0, verbose_name='Venteliste')),
                ('payments', models.IntegerField(default=0, verbose_name='Betalinger')),
                ('volunteers_male', models.IntegerField(default=0, verbose_name='Frivillige Mænd')),
                ('volunteers_female', models.IntegerField(default=0, verbose_name='Frivillige Kvinder')),
                ('volunteers', models.IntegerField(default=0, verbose_name='Frivillige')),
                ('volunteers_age_avg', models.FloatField(default=0, verbose_name='Frivillige gennemsnit alder')),
                ('volunteers_age_min', models.FloatField(default=0, verbose_name='Frivillige yngste alder')),
                ('volunteers_age_max', models.FloatField(default=0, verbose_name='Frivillige ældste alder')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStatisticsUnion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2017, 6, 7, 22, 40, 59, 9570), verbose_name='Kørsels tidspunkt')),
                ('departments', models.IntegerField(default=0, verbose_name='Afdelinger')),
                ('active_activities', models.IntegerField(default=0, verbose_name='Aktiviteter der er igang')),
                ('activities', models.IntegerField(default=0, verbose_name='Aktiviteter i alt')),
                ('current_activity_participants', models.IntegerField(default=0, verbose_name='Deltagere på aktiviteter')),
                ('current_activity_participants_age_avg', models.FloatField(default=0, verbose_name='Deltagere på aktiviteter gennemsnit alder')),
                ('current_activity_participants_age_min', models.FloatField(default=0, verbose_name='Deltagere på aktiviteter yngste alder')),
                ('current_activity_participants_age_max', models.FloatField(default=0, verbose_name='Deltagere på aktiviteter ældste alder')),
                ('activity_participants', models.IntegerField(default=0, verbose_name='Deltagere på aktiviteter over al tid')),
                ('members', models.IntegerField(default=0, verbose_name='Medlemmer')),
                ('waitinglist', models.IntegerField(default=0, verbose_name='Venteliste')),
                ('payments', models.IntegerField(default=0, verbose_name='Betalinger')),
                ('volunteers_male', models.IntegerField(default=0, verbose_name='Frivillige Mænd')),
                ('volunteers_female', models.IntegerField(default=0, verbose_name='Frivillige Kvinder')),
                ('volunteers', models.IntegerField(default=0, verbose_name='Frivillige')),
                ('volunteers_age_avg', models.FloatField(default=0, verbose_name='Frivillige gennemsnit alder')),
                ('volunteers_age_min', models.FloatField(default=0, verbose_name='Frivillige yngste alder')),
                ('volunteers_age_max', models.FloatField(default=0, verbose_name='Frivillige ældste alder')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Union')),
            ],
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='added_dtm',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tilføjet'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='on_waiting_list_since',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Venteliste position'),
            preserve_default=False,
        ),
        # Copy added_dtm from on_waiting_list_since on old records
        migrations.RunPython(forwards_func),
    ]
