# Generated by Django 1.9.1 on 2017-05-27 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0092_remove_volunteer_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='union',
            name='bank_account',
            field=models.CharField(blank=True, max_length=10, verbose_name='Kontonummer:'),
        ),
        migrations.AddField(
            model_name='union',
            name='bank_reg_number',
            field=models.CharField(blank=True, max_length=4, verbose_name='Registreringsnummer:'),
        ),
        migrations.AddField(
            model_name='union',
            name='independent_accounting',
            field=models.BooleanField(default=False, verbose_name='Selvstændig bogføring (skal kontingenter overføres?):'),
        ),
        migrations.AlterField(
            model_name='union',
            name='boardMembers',
            field=models.TextField(blank=True, verbose_name='Menige medlemmer'),
        ),
        migrations.AlterField(
            model_name='union',
            name='cashier_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Kassererens email'),
        ),
        migrations.AlterField(
            model_name='union',
            name='secratary_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Sekretærens email'),
        ),
        migrations.AlterField(
            model_name='union',
            name='secretary',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sekretær'),
        ),
    ]
