# Generated by Django 5.2.8 on 2026-01-18 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0092_merge_20260118_1751"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SlackLog",
        ),
    ]
