# Generated by Django 1.9.1 on 2017-06-08 21:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0093_auto_20170607_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailystatisticsregion',
            name='unions',
        ),
        migrations.AlterField(
            model_name='dailystatisticsdepartment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Kørsels tidspunkt'),
        ),
        migrations.AlterField(
            model_name='dailystatisticsgeneral',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Kørsels tidspunkt'),
        ),
        migrations.AlterField(
            model_name='dailystatisticsregion',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Kørsels tidspunkt'),
        ),
        migrations.AlterField(
            model_name='dailystatisticsunion',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Kørsels tidspunkt'),
        ),
    ]
