# Generated by Django 1.9.1 on 2017-05-27 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0093_auto_20170527_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='union',
            name='independent_accounting',
        ),
        migrations.AddField(
            model_name='union',
            name='bank_main_org',
            field=models.BooleanField(default=True, verbose_name='Sæt kryds hvis I har konto hos hovedforeningen (og ikke har egen bankkonto).'),
        ),
    ]
