# Generated by Django 5.2.4 on 2026-01-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0093_delete_slacklog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={
                "permissions": [
                    ("member_export_address", "Kan eksportere medlemsadresser")
                ],
                "verbose_name": "Medlem",
                "verbose_name_plural": "Medlemmer",
            },
        ),
    ]
