# Generated by Django 5.2.10 on 2026-01-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0094_alter_member_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="slackinvitationsetup",
            name="totp_secret_encrypted",
            field=models.BinaryField(
                blank=True,
                help_text="TOTP secret for Slack admin 2FA (encrypted)",
                null=True,
                verbose_name="Slack Admin TOTP Secret (Encrypted)",
            ),
        ),
    ]
