# Generated by Django 5.2.10 on 2026-02-12 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0095_slackinvitationsetup_totp_secret_encrypted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slackinvitelog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Slack Invitation Log",
                "verbose_name_plural": "Slack Invitation Logs",
            },
        ),
        migrations.AddField(
            model_name="slackinvitelog",
            name="resolution_note",
            field=models.TextField(
                blank=True,
                help_text="Evt. kommentar eller note til løsningen.",
                verbose_name="Løsningsnote",
            ),
        ),
        migrations.AddField(
            model_name="slackinvitelog",
            name="resolved",
            field=models.BooleanField(
                default=False,
                help_text="Marker hvis fejlen er håndteret/løst.",
                verbose_name="Løst/håndteret",
            ),
        ),
        migrations.AddField(
            model_name="slackinvitelog",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Tidspunkt hvor fejlen blev løst.",
                null=True,
                verbose_name="Løst tidspunkt",
            ),
        ),
        migrations.AddField(
            model_name="slackinvitelog",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Bruger der har markeret fejlen som løst.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="slack_invite_logs_resolved",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Løst af",
            ),
        ),
        migrations.AlterField(
            model_name="slackinvitationsetup",
            name="admin_password_encrypted",
            field=models.BinaryField(
                blank=True,
                help_text="Adgangskode til Slack admin-brugeren (krypteret).",
                null=True,
                verbose_name="Slack admin adgangskode (krypteret)",
            ),
        ),
        migrations.AlterField(
            model_name="slackinvitationsetup",
            name="admin_username",
            field=models.EmailField(
                blank=True,
                help_text="Emailadressen på Slack admin-brugeren der skal logges ind som.",
                max_length=254,
                verbose_name="Slack admin brugernavn",
            ),
        ),
        migrations.AlterField(
            model_name="slackinvitationsetup",
            name="emails",
            field=models.TextField(
                blank=True,
                help_text="Skriv én emailadresse per linje.",
                verbose_name="Notifikations-emailadresser",
            ),
        ),
        migrations.AlterField(
            model_name="slackinvitationsetup",
            name="invite_url",
            field=models.URLField(
                blank=True,
                help_text="URL til Slack admin invitation-siden, fx https://yourteam.slack.com/sign_in_with_password?redir=%2Fadmin%2Finvites",
                verbose_name="Slack admin invitation URL",
            ),
        ),
        migrations.AlterField(
            model_name="slackinvitationsetup",
            name="totp_secret_encrypted",
            field=models.BinaryField(
                blank=True,
                help_text="TOTP-hemmelighed til Slack admin 2FA (krypteret)",
                null=True,
                verbose_name="Slack admin TOTP hemmelighed (krypteret)",
            ),
        ),
        migrations.AlterField(
            model_name="slackinvitationsetup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Sidst opdateret"),
        ),
    ]
