# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-09 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0095_auto_20170528_1129'),
        ('members', '0095_auto_20170609_2325'),
    ]

    operations = [
    ]
