# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-09 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0096_merge'),
    ]

    operations = [
        migrations.RunSQL("UPDATE members_department SET longtitude = NULL, latitude = NULL;"),
    ]
