# Generated by Django 5.2.10 on 2026-03-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0096_alter_slackinvitelog_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slackinvitationsetup",
            options={
                "permissions": [
                    ("can_approve_slack_invites", "Can approve Slack invites")
                ],
                "verbose_name": "Slack Invitation Setup",
                "verbose_name_plural": "Slack Invitation Setup",
            },
        ),
        migrations.AlterField(
            model_name="slackinvitelog",
            name="resolved",
            field=models.BooleanField(
                default=False,
                help_text="Marker hvis fejlen er håndteret/løst. Sættes automatisk hvis status er 'Invite used' eller 'Error handled'.",
                verbose_name="Løst/håndteret",
            ),
        ),
        migrations.AlterField(
            model_name="slackinvitelog",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Oprettet"),
                    (2, "Invitation fejlede"),
                    (3, "Fejl håndteret"),
                    (4, "Slack invitation udført"),
                ],
                default=1,
            ),
        ),
    ]
