# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-28 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0097_clearLongLat'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.Union'),
        ),
    ]
