# Generated by Django 5.2.10 on 2026-03-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0097_alter_slackinvitationsetup_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slackinvitelog",
            name="email",
        ),
        migrations.AddField(
            model_name="slackinvitelog",
            name="emails",
            field=models.TextField(blank=True),
        ),
    ]
