# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-11 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0097_auto_20170612_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breddegrad'),
        ),
        migrations.AlterField(
            model_name='department',
            name='longtitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Længdegrad'),
        ),
    ]
