# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-12 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0097_auto_20170612_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityinvite',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='En VIP kan deltage i en aktivitet selv om der ikke er flere pladser', verbose_name='VIP'),
        ),
    ]
