# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-12 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0097_auto_20170612_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityinvite',
            name='override_price_in_dkk',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Special pris'),
        ),
    ]
