# Generated by Django 5.2.10 on 2026-03-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0098_remove_slackinvitelog_email_slackinvitelog_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackinvitelog",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Oprettet"),
                    (2, "Invite used"),
                    (3, "URL failed/email sent"),
                    (4, "Slack invitation udført"),
                    (5, "Invitation fejlede"),
                    (6, "Fejl håndteret"),
                ],
                default=1,
            ),
        ),
    ]
