# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-19 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0099_updateLongLatError'),
        ('members', '0098_auto_20170719_1240'),
    ]

    operations = [
    ]
