# Generated by Django 5.2.10 on 2026-03-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0099_alter_slackinvitelog_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="slackinvitelog",
            name="resolved",
        ),
    ]
