# Generated by Django 5.2.10 on 2026-03-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0088_activityinvite_reminder_sent_at"),
        ("members", "0100_remove_slackinvitelog_resolved"),
    ]

    operations = []
