# Generated by Django 5.2.10 on 2026-03-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0100_remove_slackinvitelog_resolved"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="consent_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Samtykke-/inaktivitetspåmindelse sendt",
            ),
        ),
    ]
