# Generated by Django 5.2.10 on 2026-05-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0100_remove_slackinvitelog_resolved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="union",
        ),
    ]
