# Generated by Django 5.2.10 on 2026-05-03 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0101_merge_20260329_1428"),
        ("members", "0101_person_consent_reminder_sent_at"),
    ]

    operations = []
