# Generated by Django 5.2.10 on 2026-05-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0101_merge_20260329_1428"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityinvite",
            name="invitation_decline_uuid",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="UUID til at afvise invitationen"
            ),
        ),
    ]
