# Generated by GitHub Copilot on 2026-05-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0101_merge_20260329_1428"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="municipality",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=models.RESTRICT,
                to="members.municipality",
            ),
        ),
    ]
