# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-19 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0102_auto_20170828_1529'),
        ('members', '0102_clear_long_lat'),
    ]

    operations = [
    ]
