# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-21 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import members.managers


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0102_auto_20170804_1621'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('objects', members.managers.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
