# Generated by Django 5.2.10 on 2026-05-03 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0102_activityinvite_invitation_decline_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="family",
            name="unique",
        ),
    ]
