# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-19 23:19
from __future__ import unicode_literals

from django.db import migrations

def reset_LatLon(apps, schema_editor):
    Department = apps.get_model('members', 'Department')
    deps = Department.objects.all()
    for dep in deps:
        dep.longitude = None
        dep.latitude = None
        dep.save()

class Migration(migrations.Migration):

    dependencies = [
        ('members', '0103_merge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='longtitude',
            new_name='longitude',
        ),
        migrations.RunPython(reset_LatLon),
    ]
