# Generated by Django 5.2.10 on 2026-05-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0103_remove_family_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="family",
            options={"verbose_name": "Familie", "verbose_name_plural": "Familier"},
        ),
        migrations.RenameField(
            model_name="activityinvite",
            old_name="invitation_decline_uuid",
            new_name="decline_uuid",
        ),
    ]
