# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-20 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0104_auto_20180120_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='added_dtm',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tilføjet'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='on_waiting_list_since',
            field=models.DateTimeField(verbose_name='Venteliste position'),
        ),
    ]
