# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-30 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0099_volunteer_confirmed'),
        ('members', '0104_auto_20180120_0019'),
    ]

    operations = [
    ]
