# Generated by Django 5.2.10 on 2026-05-03 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0104_alter_family_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityinvite",
            name="decline_uuid",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                null=True,
                unique=True,
                verbose_name="UUID til at afvise invitationen",
            ),
        ),
    ]
