# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-20 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Waitinglist = apps.get_model("members", "Waitinglist")
    db_alias = schema_editor.connection.alias
    for waitinglistItem in Waitinglist.objects.using(db_alias).all():
        waitinglistItem.on_waiting_list_since = waitinglistItem.person.added
        waitinglistItem.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0104_auto_20180120_0019'),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='waitinglist',
            name='added_dtm',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tilføjet'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='on_waiting_list_since',
            field=models.DateTimeField(verbose_name='Venteliste position'),
        ),
    ]
