# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-13 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0105_merge'),
        ('members', '0105_waitinglist_dates'),
    ]

    operations = [
    ]
