# Generated by Django 5.2.10 on 2026-05-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0102_merge_20260503_1425"),
        ("members", "0105_alter_activityinvite_decline_uuid"),
    ]

    operations = []
