# Generated by Django 5.2.10 on 2026-06-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0106_merge_20260503_1433"),
        ("members", "0106_merge_20260503_1444"),
    ]

    operations = []
