# Generated by Django 5.2.10 on 2026-06-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0106_merge_20260503_1444"),
    ]

    operations = [
        migrations.AddField(
            model_name="municipality",
            name="region",
            field=models.CharField(blank=True, max_length=30, verbose_name="Region"),
        ),
    ]
