# Generated by Django 5.2.10 on 2026-06-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0107_merge_20260607_1103"),
        ("members", "0107_municipality_region"),
    ]

    operations = []
