# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-28 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0107_person_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Breddegrad'),
        ),
        migrations.AddField(
            model_name='person',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Længdegrad'),
        ),
    ]
