# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-09-29 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0108_auto_20180928_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address_invalid',
            field=models.BooleanField(default=False, verbose_name='Ugyldig adresse'),
        ),
    ]
