# Generated by Django 5.2.10 on 2026-06-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0108_merge_20260607_1530"),
        ("members", "0108_merge_20260607_1555"),
    ]

    operations = []
