# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-01-14 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0109_person_address_invalid'),
        ('members', '0103_person_user'),
    ]

    operations = [
    ]
