# Generated by Django 5.2.10 on 2026-07-12 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0109_merge_20260607_1643"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Betaling", "verbose_name_plural": "Betalinger"},
        ),
    ]
