# Generated by Django 5.2.10 on 2026-06-15 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0092_volunteer_user_confirmation_status"),
        ("members", "0109_merge_20260607_1643"),
    ]

    operations = []
