# Generated by Django 5.2.10 on 2026-07-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0109_merge_20260607_1643"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityinvite",
            name="decline_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Grund til afslag"
            ),
        ),
    ]
