# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-01-21 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0110_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='membership_activity',
            field=models.BooleanField(default=False, verbose_name='Er aktiviteten en medlemsskabsaktivitet?'),
        ),
    ]
