# Generated by Django 5.2.10 on 2026-08-23 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0110_activityinvite_decline_reason"),
        ("members", "0110_alter_payment_options"),
    ]

    operations = []
