# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-04 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0111_activity_membership_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='door',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Dør'),
        ),
        migrations.AlterField(
            model_name='person',
            name='floor',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Etage'),
        ),
        migrations.AlterField(
            model_name='person',
            name='placename',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stednavn'),
        ),
    ]
