# Generated by Django 5.2.10 on 2026-08-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0111_alter_volunteerrequestitem_status"),
        ("members", "0111_merge_20260823_1218"),
    ]

    operations = []
