# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-04 11:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0112_auto_20190204_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='membership_activity',
        ),
        migrations.AlterField(
            model_name='activity',
            name='department',
            field=models.ForeignKey(help_text='Vi tilføjer automatisk "Coding Pirates" foran navnet når vi nævner det de fleste steder på siden.', on_delete=django.db.models.deletion.CASCADE, to='members.Department'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='price_in_dkk',
            field=models.DecimalField(decimal_places=2, default=500, help_text='På prisen for aktiviteten fratrækker vi automatisk 75 kr. pr. barn hvis det er en sæsonaktivitet.', max_digits=10, verbose_name='Pris'),
        ),
    ]
