name: Prepare deploy

on: [pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Enviroment
        run: cp .env.example .env
      - name: Builds the stack
        run: docker-compose build
      - name: Test
        run: docker-compose run web ./manage.py test
      - name: Check formatting
        uses: lgeiger/black-action@v1.0.1
      - name: Static error check (Flake8)
        uses: cclauss/GitHub-Action-for-Flake8@v0.5.0
      
