name: Run tests & Analyse code

on: [push, pull_request]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Enviroment
        run: cp .env.example .env
      - name: Builds the stack
        run: docker-compose build
      - name: Test
        run: docker-compose run web ./manage.py test
      - name: Check formatting (Black)
        run: docker-compose run web black --check .
      - name: Static error check (Flake8)
        run: docker-compose run web flake8
      - name: Create and upload UML diagram
        uses: actions/upload-artifact@v1
        with:
          name: my-artifact
          path: path/to/artifact
        run: "mkdir -p UML && docker-compose run web \
          ./manage.py graph_models members -o UML/members_models.png"
